### ISSUE TITLE
Running VisIT on a remote host

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#108]
Hi all,

I am trying to run VisIT on a remote host. I can easily connect my VPN to the internal network. I can easily SSH to the remote host in the usual fashion through the terminal window. Once ssh’ed in I can access all SSD locations and files. I can run codes like FLASH remotely at this point with standard mpirun or nohup mpirun. I can launch VisIT on the remote host via an SSH connection with the line command:

 /Applications/VisIt.app/Contents/Resources/bin/visit -np 12

Visit happily launches on the remote host and I can actually use it while sitting at the remote host. My terminal window on the local machine sits and does nothing. This is as expected.

I then go into VisIT on my local machine and setup a remote host profile following the detailed instructions in the manual. Everything proceeds normally. When I try to open a file using the remote host name, I get the correct ssh request for a password. I enter the password and get the following VisIT error:

******************
The metadata server on host xxxxx.lle.rochester.edu could not be launched or it could not connect back to your local computer. This can happen for a variety of reasons.

The specific error was: "<The reason for the exception was not described>"

It is possible that SSH was unable to launch VisIt on xxxxx.lle.rochester.edu. If you want to verify this, run "visit -debug 5" and then check to see if any vcl, mdserver, or engine log files are present on xxxxx.lle.rochester.edu in your home directory. If no log files were created then SSH was probably not able to launch VisIt components on blackbuild.lle.rochester.edu. In that case, check that you can SSH to blackbuild.lle.rochester.edu and check your local VisIt installation's Host profiles to make sure the path to VisIt on blackbuild.lle.rochester.edu is specified. Alternatively, you set the PATH environment variable on blackbuild.lle.rochester.edu so it contains the path to the program "visit”.

.
.
.

******************

It acts like it cannot find VisIT.

The path I used in the host setup is /Applications/. That is the path I get with pwd in the directory with VisIT.

Suggestions? This is likely a stupid mistake.

Rick

Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Rick,

You probably want to specify the path as:

/Applications/VisIt.app/Contents/Resources

When running a remote version it will add "bin/visit" to the path you specified to get the location of the launch script.

If that doesn't work, then it would be useful to know what OS you are running on the remote system.

Eric

**Comment by markcmiller86-visit** [comment]
Dear Eric,

I tried your suggestion and things still did not work. I got nearly the same error message:

********
The metadata server on host xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu> could not be launched or it could not connect back to your local computer. This can happen for a variety of reasons.

The specific error was: "<The reason for the exception was not described>"

It is possible that SSH was unable to launch VisIt on xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu>. If you want to verify this, run "visit -debug 5" and then check to see if any vcl, mdserver, or engine log files are present on xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu> in your home directory. If no log files were created then SSH was probably not able to launch VisIt components on xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu>. In that case, check that you can SSH to xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu> and check your local VisIt installation's Host profiles to make sure the path to VisIt on xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu> is specified. Alternatively, you set the PATH environment variable on xxxxx.lle.rochester.edu<http://xxxxx.lle.rochester.edu> so it contains the path to the program "visit”.
.
.
********

I ran VisIT in -debug 5 mode on my local machine and the terminal window says host key verification failed.

I attached a debug log.  Suggestions? I am using the default ssh port 22.

Rick


Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu<mailto:spielman@lle.rochester.edu>



On Jul 16, 2020, at 5:12 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

You probably want to specify the path as:

/Applications/VisIt.app/Contents/Resources

When running a remote version it will add "bin/visit" to the path you specified to get the location of the launch script.

If that doesn't work, then it would be useful to know what OS you are running on the remote system.

Eric

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_108-23issuecomment-2D659675609&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=NqWcczkpP12D0uAO5zJ2JjFnJHoect_ieaI-2DhTRMg&s=lmWDyGpQWqrlqILXuZarnZObNioShoZRxT3Z5l1RDc4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZF3VOKL7B3DLF4EAADR35ULFANCNFSM4O45WEEQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=NqWcczkpP12D0uAO5zJ2JjFnJHoect_ieaI-2DhTRMg&s=xVY8oOXSTFn9tPIBX1GnDVlUJmFAVS-StJFXFpGjkRs&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=NqWcczkpP12D0uAO5zJ2JjFnJHoect_ieaI-2DhTRMg&s=89VeB2TspGJqFD_sfV2r_0D3Hw2Y44m1FDY0gqmNVhs&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=NqWcczkpP12D0uAO5zJ2JjFnJHoect_ieaI-2DhTRMg&s=mT6Dr_DU_NLbJY5yX9SPIsYWLGiBPliIsn_rvZ2meQ4&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=NqWcczkpP12D0uAO5zJ2JjFnJHoect_ieaI-2DhTRMg&s=DHVdIqkbhKARGQ0I44_MPTbkKuz_NoO2znLXkj1-4Eg&e=

**Comment by brugger1** [comment]
Hi Rick,

Can you check if there are any vlog files on the remote host? They would be in your home directory on a Linux system. I don't know where they would be on another system. That would at least let us know if VisIt is successfully logging into the remote system and finding VisIt.

Another thing to try is running directly on the remote system with your host profiles. This would make it easier to debug any host profile issues, since it avoids any networking issues.

Eric

**Comment by markcmiller86-visit** [comment]
Dear Eric,

There is no vlog file on the remote host.

Running VisIT on the remote host with the localhost works perfectly.

The path on the open dialog is correctly to the data files.

If I try create a new host profile in VisIT on the remote host directly it does not work. Again, it is likely the path.

If you have explicit things for me to try I will do that.

Rick


On Jul 17, 2020, at 1:30 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

Can you check if there are any vlog files on the remote host? They would be in your home directory on a Linux system. I don't know where they would be on another system. That would at least let us know if VisIt is successfully logging into the remote system and finding VisIt.

Another thing to try is running directly on the remote system with your host profiles. This would make it easier to debug any host profile issues, since it avoids any networking issues.

Eric

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_108-23issuecomment-2D660242558&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=cm_S_Xzr_Sg6DIpd3s9PFgfpo2dvNgVI2q0BgvI0hAQ&s=zLqTIiOOKOt4KmjN9LWAUuuzJTh39Rj1vGm-w2E685A&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZFRDTXXC4KKLKTEUDLR4CDDHANCNFSM4O45WEEQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=cm_S_Xzr_Sg6DIpd3s9PFgfpo2dvNgVI2q0BgvI0hAQ&s=Nua0w_Y6Eges1N5GfKZySNe7UXnrIlyTCbwEpYdqhhQ&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=cm_S_Xzr_Sg6DIpd3s9PFgfpo2dvNgVI2q0BgvI0hAQ&s=nEMTRDgT_sOB0x9anM0gIcu_YzasMsRTalW23xBPMEA&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=cm_S_Xzr_Sg6DIpd3s9PFgfpo2dvNgVI2q0BgvI0hAQ&s=GtSEhHWoF0_jIdVuJQYpoc9JWjXsGq0sDAgGpWPVIwY&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=cm_S_Xzr_Sg6DIpd3s9PFgfpo2dvNgVI2q0BgvI0hAQ&s=HdVOeQBFejRsaK4gsGRN-yp_nXTV_2CQm39cH9rDa2E&e=

**Comment by brugger1** [comment]
Hi Rick,

Can you tell me what OS you are running on the remote system? Also, can you list the contents of

/Applications/VisIt.app/Contents/Resources

Eric

**Comment by markcmiller86-visit** [comment]
Dear Eric,

I am running macOS Catalina on the remote host and macOS Mojave on the local machine. The local machine is running VisIT 2.13 and the remote host is running VisIT 3.1.

blackbuild:Resources spielman$ ls
3.1.1 VisIt.icns bin data

Rick



On Jul 17, 2020, at 2:19 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

Can you tell me what OS you are running on the remote system? Also, can you list the contents of

/Applications/VisIt.app/Contents/Resources

Eric

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_108-23issuecomment-2D660267167&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=dj-iuwG4elZBZUyfRE6Hve1Kg0XA9mDdAhBNKdA_TZs&s=HtcN9h4CTtp-DLftrTwxCDiZjfK1lfrHsO9xs5_nFZk&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZGTHKN2QCYP5YIED6DR4CI3NANCNFSM4O45WEEQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=dj-iuwG4elZBZUyfRE6Hve1Kg0XA9mDdAhBNKdA_TZs&s=g1EpWwk4QsdRS6FoeIOgQbjUrr-5hhfJOl4taxlFBto&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=dj-iuwG4elZBZUyfRE6Hve1Kg0XA9mDdAhBNKdA_TZs&s=SRvE2SWYiGQOI4dN7FscTx0rVZjM8WOUXPxj7qYGLzM&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=dj-iuwG4elZBZUyfRE6Hve1Kg0XA9mDdAhBNKdA_TZs&s=fNdtnRc6tUPLWxu0lOftwJT-Rh9T4CYVCarLXEys_4g&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=dj-iuwG4elZBZUyfRE6Hve1Kg0XA9mDdAhBNKdA_TZs&s=hu-BGU65EVQWHed-SFxuhVjUupNZg4hZhsx4ZcPPpZU&e=

**Comment by brugger1** [comment]
Hi Rick,

Ah, just got the key piece of information.

When running client server the versions of VisIt must match in the first 2 digits. So, 3.1 and 2.13 won't work together. You must use either 3.1 for both local and remote or 2.13 for both local and remote.

Eric

**Comment by markcmiller86-visit** [comment]
Dear Eric,

I have deleted the newer version of VisIT and have V2.13 on both machines.

My VPN is good and I can ssh into my remote host perfectly

vpn92:~ rbspielman$ ssh spielman@blackbuild.lle.rochester.edu<mailto:spielman@blackbuild.lle.rochester.edu>
Password:
Last login: Fri Jul 17 14:26:28 2020

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
blackbuild:~ spielman$

My host window is:

[cid:EE273156-F9B3-4DA5-B551-6E827DC5050A]

I am not sure about the SSH port. I am not even getting into the computer. The terminal window for VisIT shows.

tvpn92:~ rbspielman$ /Applications/VisIt.app/Cont5 -np 4sources/bin/visit -debug 5
Running: gui2.13.3 -debug 5 -engineargs -l;mpiexec;-np;4 -launchengine localhost
Running: viewer2.13.3 -debug 5 -engineargs -l;mpiexec;-np;4 -geometry 1020x835+420+3 -borders 20,0,0,1 -shift 0,0 -preshift 0,0 -defer -host 127.0.0.1 -port 5600 -launchengine localhost
Running: mdserver2.13.3 -debug 5 -host 127.0.0.1 -port 5601
Running: /Applications/VisIt.app/Contents/Resources/2.13.3/darwin-x86_64/bin/mpiexec -n 4 /Applications/VisIt.app/Contents/Resources/2.13.3/darwin-x86_64/bin/engine_par -plugindir /Users/rbspielman/.visit/2.13.3/darwin-x86_64/plugins:/Applications/VisIt.app/Contents/Resources/2.13.3/darwin-x86_64/plugins -visithome /Applications/VisIt.app/Contents/Resources/2.13.3 -visitarchhome /Applications/VisIt.app/Contents/Resources/2.13.3/darwin-x86_64 -debug 5 -host 127.0.0.1 -port 5600
Password:
Host key verification failed.
Password:
Host key verification failed.
Password:Password:
Host key verification failed.

Thoughts,

Rick

On Jul 17, 2020, at 2:46 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

Ah, just got the key piece of information.

When running client server the versions of VisIt must match in the first 2 digits. So, 3.1 and 2.13 won't work together. You must use either 3.1 for both local and remote or 2.13 for both local and remote.

Eric

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_108-23issuecomment-2D660279556&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Em38jHtHNvlza-h_m-D74jOLyAwGHvbxKrGQAbemr9U&s=Ufwxc-EhFe-zmVG5k60FtEhZlua9xq4J2iO-hYroz24&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZDC2BQJAJU3HIGA4ALR4CL7HANCNFSM4O45WEEQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Em38jHtHNvlza-h_m-D74jOLyAwGHvbxKrGQAbemr9U&s=t6ZezHUKk9SXv--OlOn1zC6hYCK3XcLcoVtxKLUMUfw&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Em38jHtHNvlza-h_m-D74jOLyAwGHvbxKrGQAbemr9U&s=zxTbOjcs5VscpbUDZ_skg5ssAM-5lMzUTz3yVySmX7Y&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Em38jHtHNvlza-h_m-D74jOLyAwGHvbxKrGQAbemr9U&s=GEOjU8cjmpRH_14EP1orAqJNkkPjQYMHTmaBny3ITj4&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Em38jHtHNvlza-h_m-D74jOLyAwGHvbxKrGQAbemr9U&s=qlLH9M8Wf9AK6V69N_Dx5LmGeootDlohU9rk7jAmItQ&e=

**Comment by brugger1** [comment]
At this point the only thing I can suggest is to install 3.1.1 on both the local and remote systems, since you got further logging into the remote system with 3.1.1. I'm have no experience running client/server between 2 mac systems, so I will need to see if anyone else has any ideas on what the correct path should be.

**Comment by griffin28** [comment]
Hello Rick...this looks more like an SSH issue now than an issue with VisT or maOS. Here's a link that can help you fix your 'Host key verification failed' issue: https://www.thegeekdiary.com/how-to-fix-the-error-host-key-verification-failed/
