### ISSUE TITLE
Performance bottleneck creating ghost zones for materials

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#139]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I'm visualizing some data that contains two materials.  In some cases, I want to turn off one material to see the boundary between them and the data on that boundary.  This isn't a problem functionally - I turn off the material in a Pseudocolor plot I don't want to see and VisIt constructs the boundary and colors it.

The problem I'm having is for larger data sets there seems to be a significant bottleneck in creating ghost zones (stage 5 in my case).  Specifically, in "Creating ghost zones for materials".  Is there anything I can do to improve the performance of this (sub)stage or the overall performance of the visualization?

Thanks for any and all help...
Terry

**Comment by rusu24edward** [comment]
Hi Terry,

Are you running Visit in parallel? How many domains does your dataset have?

**Comment by markcmiller86-visit** [comment]
Another useful piece of information would be the mesh type. Is it structured or AMR?

**Comment by tjligocki-lbl** [comment]
I'm running VisIt in parallel (on NERSC Cori with 1024 processes).  Each timestep in the dataset is 25GB and each contain 2 materials - is that what you mean by "domains"?  If not, let me know what you do mean and how I would determine the answer.  Also, the overall size is 1536 x 64 x 512 cells.  It is AMR data BUT there is only one level which is simply decomposed into 32 x 32 x 32 boxes of cells so there are 1536 boxes.

This dataset was generated by Chombo and output in the Chombo AMR format (which VisIt reads).  I can also provide a timestep of data if that would be helpful.

**Comment by rusu24edward** [comment]
Hi Terry,

If you click on the tiny "Venn diagram" icon, the subset window will appear. Here, I'm looking at a dataset with 3 materials and 36 domains:
![materials](https://user-images.githubusercontent.com/18565891/92531055-71a89d00-f1e2-11ea-84ee-ac776cd28cca.png)
![domains](https://user-images.githubusercontent.com/18565891/92531065-779e7e00-f1e2-11ea-940c-435ca0d40110.png)

Yes, a timestep of data would be very helpful. Can you give me, `rusu1`, the data on LC?

**Comment by tjligocki-lbl** [comment]
Thanks for the images - always helpful, :-).  Since this is AMR data with 1 level there are three submenus under "Mesh" and they are "levels", "patches", and "materials".  The "levels" opens up to "level0" (there's only one level in this computation) and it is selected.  The "patches" opens up to "level0,patch0" ... "level0,patch1535" (1536 patches).  The "materials" opens up to "mat1" and "mat2".  In the case I'm reporting, I've selected "mat1" and deselected "mat2".

I currently have the data on NERSC Cori but I suspect you can't read it.  It looks like we don't share any groups on Cori but I could make one timestep world readable in a directory you could also access.  I'm not familiar with the abbreviation "LC" so I don't know how to give you, rusu1, the data on LC but I'd be happy to do so...

**Comment by rusu24edward** [comment]
Got it, thanks for the info. So it looks like the vernacular is patches/boxes = domains.

Sorry about the confusion with LC, I misread your email address and thought it said llnl, not lbl. @brugger1 has an active account on Cori. Can you share the data with him (his username is `brugger`)?

**Comment by brugger1** [comment]
Yes, my user name is "brugger".

**Comment by tjligocki-lbl** [comment]
It looks like we share a group, "m1792", and the data should be accessible to you.  I'll send the details to your LLNL email if that's okay.

**Comment by brugger1** [comment]
That works for me.

**Comment by tjligocki-lbl** [comment]
I sent an e-mail to "brugger1@llnl.gov"...

**Comment by ghweber** [comment]
Hi, the ghost zone performance could be related to changes long ago that enabled extraction of crack free isosurfaces from AMR data. One way to test if this is at least partially responsible is to start VisIt with the option "-disable-ghosts-for-t-intersections" and see if the problem improves.

More detailed explanation: VisIt originally only computed ghost zones within an AMR level. To enable crack free ios-surface extraction we changed this so that ghost cells at level boundaries were initialized from the coarser level. While this enables crack free isosurfaces on AMR data (using the AMRStitchCell operator), it also seems to make ghost zone generation more expensive. Using the option "-disable-ghosts-for-t-intersections" reverts to the original behavior.

**Comment by brugger1** [comment]
That’s a good point. I normally associate that with increased memory usage, but it could also have a performance impact as well.

**Comment by tjligocki-lbl** [comment]
I tried producing the visualization with and without the "-disable-ghosts-for-t-intersections" (thanks for the suggestion Gunther).  With the flag a frame took 3:45 minutes and without it took 16:53 minutes!  So, the flag made a huge difference.  In both cases, most of the time was spent in "Creating ghost zones for materials" (see above) BUT obviously as lot longer without the flag.

I'm a bit surprised this was true for this dataset since it only has one level - there are no coarser levels to initialize the finer levels and no coarse/fine boundaries...

**Comment by ghweber** [comment]
I am surprised as well. If there is just one level, there shouldn't be a difference between the two. So something seems to go seriously wrong. Unfortunately I do not know how the ghost zone generation code works as Hank Childs and Jeremy Meredith were handling that part of the implementation. But I would guess that there is a problem in setting up the structured domain boundaries or the nested domain boundaries structures.

**Comment by ghweber** [comment]
Hi,

Since this issue pops up every now and then, it may be a good idea to file a feature request for VisIt to make this configurable. When we made the new behavior default for VisIt, we were not aware of the memory and performance hit taken. I'd suggest to move switching ghost zone generation behavior from a command line options to the VisIt options GUI menu and possibly revert to the old behavior by default. The AMRStitchCell operator could detect that setting and print a warning/error asking the use to change that option. That way only users actually using crack free isosurfaces for AMR would be impacted.

@brugger1 what do you think?
