### ISSUE TITLE
Pseudo color image looks like a filled boundary plot.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#156]
Barb tried out VisIt 3.1.2, moving up from 2.13.3 and she did a pseudocolor plot of a variable and it looked like a filled boundary plot to her with distinct colors in various sections of the data.

She sent me a picture and it looked like she had used a discrete color table to me.

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
After some investigation, we found that the pseudocolor plot uses the "Default" colormap and she had her Default color maps for both the continuous and discrete set to the same discrete color map. She doesn't know how that happened, but it was the cause of her confusion.

I agree, this is strange, but it is probably because she has a lot of custom color maps and perhaps she set the defaults without realizing the implication and until we changed the pseudocolor plot default to be "Default", it may never have even mattered. I expect only a user that heavily customizes VisIt would ever run into this.

**Comment by markcmiller86** [comment]
A while back, more than a year probably but not so far back it was before 2.12.3 which is the version Barb was previously using I think, we discovered a few plots in VisIt that had their default attributes for colormap set to a specific colormap (hot I think) instead of set to *default*...meaning to use whatever the default (discrete or continuous depending on context) color map was. We updated those plots to all have their default attributes color map set to use default color map, not hot. At that point, anyone with a default color map setting other than hot would have noticed a change. So, I think that is what happened with Barb.
