### ISSUE TITLE
Trouble access data from hard disk in Macbook Air

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#160]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,
 
I use a Macbook Air and I am facing trouble accessing data from my hard disk. I want to load some very large .vtk files from my external HDD into Visit but when I try to double click the HDD option under ‘Open’ it displays a ‘Metadata’ error.
 
Can someone explain what might be the case and how I can access data from my HDD into Visit?
 
Thanks
 
Riddhi

**Comment by rusu24edward** [comment]
Hi Riddhi,

I'm sorry that you are having this trouble. What's the exact error message you get?

**Comment by markcmiller86-visit** [comment]
Hi Edward,

Sorry I should have been more specific. I get the following error message when I double click on the HDD name to load data:

“The MetaData server running on localhost could not get the file list for the current directory.”

Riddhi


From: Edward Rusu via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, October 13, 2020 at 8:07 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Edward Rusu <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)


Hi Riddhi,

I'm sorry that you are having this trouble. What's the exact error message you get?

**Comment by markcmiller86** [comment]
This smells an awful lot like this issue...

https://github.com/visit-dav/visit/issues/4069

If so, try launching from Terminal app command-line instead by clicking icon

Mark


"markcmiller86-visit" wrote:

Hi Edward,

Sorry I should have been more specific. I get the following error message when I double click on the HDD name to load data:

“The MetaData server running on localhost could not get the file list for the current directory.”

Riddhi


From: Edward Rusu via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, October 13, 2020 at 8:07 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Edward Rusu <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)


Hi Riddhi,

I'm sorry that you are having this trouble. What's the exact error message you get?

**Comment by markcmiller86-visit** [comment]
Thanks a lot Mark. That actually worked!
What is the reason for this distinction between launching Visit by double clicking the app-bundle and launching it via Terminal? Is this going to be taken care of in a future update?

Riddhi

From: "Mark C. Miller via visit-users" <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, October 14, 2020 at 10:27 AM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: "Mark C. Miller" <notifications@github.com>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)

This smells an awful lot like this issue...

https://github.com/visit-dav/visit/issues/4069

If so, try launching from Terminal app command-line instead by clicking icon

Mark


"markcmiller86-visit" wrote:

Hi Edward,

Sorry I should have been more specific. I get the following error message when I double click on the HDD name to load data:

“The MetaData server running on localhost could not get the file list for the current directory.”

Riddhi


From: Edward Rusu via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, October 13, 2020 at 8:07 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Edward Rusu <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)


Hi Riddhi,

I'm sorry that you are having this trouble. What's the exact error message you get?

**Comment by markcmiller86** [comment]
"markcmiller86-visit" wrote:

Thanks a lot Mark. That actually worked!
What is the reason for this distinction between launching Visit by double clicking the app-bundle and launching it via Terminal?

We don’t fully understand the issue yet.

Is this going to be taken care of in a future update?

Absolutely

**Comment by griffin28** [comment]
In the **Security & Privacy** settings in the **Automation** tab make sure you allow VisIt.app and viewer.app to control Terminal (see image attached). This should allow the correct execution when clicking the icon.

<img width="780" alt="Screen Shot 2020-10-14 at 11 09 37 AM" src="https://user-images.githubusercontent.com/26772741/96028422-1d5e9180-0e0e-11eb-9754-3831bfe003cd.png">

**Comment by markcmiller86-visit** [comment]
Hi Kevin,

Thanks for the suggestion but under ‘Automation’, the Visit app doesn’t show up. Why must that be?

Riddhi
From: Kevin Griffin via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, October 14, 2020 at 2:13 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kevin Griffin <notifications@github.com>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)


In the Security & Privacy settings in the Automation tab make sure you allow VisIt.app and viewer.app to control Terminal (see image attached). This should allow the correct execution when clicking the icon.

[Screen Shot 2020-10-14 at 11 09 37 AM]<https://user-images.githubusercontent.com/26772741/96028422-1d5e9180-0e0e-11eb-9754-3831bfe003cd.png>

**Comment by markcmiller86-visit** [comment]
Hello,

I have the following query: I have 2D map for which I am plotting a Lineout curve along the X direction, my endpoints being (-300, 0, 0) and (200, 0, 0). Lineout plots distance on X axis from 0 to 500 (length in the x dimension). However, I wish to change the X axis range of the plot to look similar to the x axis of my 2D map,  that is, going from -300 to 200 instead of being shifted by 300. Does Visit allow this? If so, can someone direct me how to do it?

Thank you.

Riddhi


From: Riddhi A Mehta via visit-users <visit-users@elist.ornl.gov>
Date: Wednesday, October 14, 2020 at 10:39 AM
To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>, visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Riddhi A Mehta <mehta74@purdue.edu>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>, Mark C. Miller <notifications@github.com>
Subject: Re: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)
Thanks a lot Mark. That actually worked!
What is the reason for this distinction between launching Visit by double clicking the app-bundle and launching it via Terminal? Is this going to be taken care of in a future update?

Riddhi

From: "Mark C. Miller via visit-users" <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Wednesday, October 14, 2020 at 10:27 AM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: "Mark C. Miller" <notifications@github.com>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)

This smells an awful lot like this issue...

https://github.com/visit-dav/visit/issues/4069

If so, try launching from Terminal app command-line instead by clicking icon

Mark


"markcmiller86-visit" wrote:

Hi Edward,

Sorry I should have been more specific. I get the following error message when I double click on the HDD name to load data:

“The MetaData server running on localhost could not get the file list for the current directory.”

Riddhi


From: Edward Rusu via visit-users <visit-users@elist.ornl.gov>
Reply-To: visit-dav/live-customer-response <reply@reply.github.com>, VisIt software users community <visit-users@elist.ornl.gov>
Date: Tuesday, October 13, 2020 at 8:07 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Edward Rusu <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Trouble access data from hard disk in Macbook Air (#160)


Hi Riddhi,

I'm sorry that you are having this trouble. What's the exact error message you get?
