### ISSUE TITLE
Unable to interact with VisIt on VNC

### ISSUE THREAD

**Issue by aowen87** [visit-dav/live-customer-response#162]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

I'm suddenly unable to interact with VisIt when on RZ VNC... I can launch VisIt, but I can't click any of the buttons. Is anyone else seeing this issue?
I thought it might be an issue with my session, so I tried vnckill, but it didn't have any affect.

**Comment by rusu24edward** [comment]
I had the same issue. I emailed LC hotline about it, here's the response I got:

"General slowness can be caused by a number of things.  It could be a load issue with VNC, whether or not you're using VPN, your ISP, etc.
 
As a last resort, you can restart your VNC session by first issuing the vnckill command, then start from scratch.
Barna"

I was able to launch from an mxterm without issue.

**Comment by brugger1** [comment]
I've been have slowness problems just now as well and it looks like it just got better again. Typing in the terminal was slow, refreshing the terminal window was slow and the background would change into strange colors.

**Comment by aowen87** [comment]
Strange... It sounds like there's just some issues going on with VNC today. Thanks for the feedback!
