### ISSUE TITLE
Lineout plot X axis range query

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#166]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello,

I have the following query: I have 2D map for which I am plotting a Lineout curve along the X direction, my endpoints being (-300, 0, 0) and (200, 0, 0). Lineout plots distance on X axis from 0 to 500 (length in the x dimension). However, I wish to change the X axis range of the plot to look similar to the x axis of my 2D map,  that is, going from -300 to 200 instead of being shifted by 300. Does Visit allow this? If so, can someone direct me how to do it?

Thank you.

Riddhi

**Comment by biagas** [comment]
Hello Riddhi,

There isn't a way to do it directly.
You can save the curve as a vtk file, open it in VisIt, create a Mesh plot, then apply the Transform operator using the Scale option.

To save the curve as vtk, make sure the window that contains the lineout is active, then open File->Set save options
Make note of where the file is being saved, enter a filename, turn off family if desired (it appends a 4-digit number to the filename). Set type to VTK, then Save and dismiss.

![SetSaveOptions](https://user-images.githubusercontent.com/17075318/96657906-37114480-12f8-11eb-99c2-60907e5e5def.PNG)

Once saved, open the saved file in VisIt, create a Mesh plot (you can change the color if you want).
Apply the Transform operator, set the Scale option:

![TransformOp](https://user-images.githubusercontent.com/17075318/96658020-73dd3b80-12f8-11eb-981f-bff446bd27aa.PNG)

**Comment by markcmiller86-visit** [comment]
Hi Kathleen,

Thank you very much for a detailed response! I think however, that the Translate option is appropriate for the task I want to achieve rather than the Scale since I want to translate the entire x-axis by -300 to match my 2D bounds. But the procedure you outlined was extremely helpful to achieve that.

However, I have one more question. When I create the Mesh plot it is quite tiny, see below:

[A picture containing text  Description automatically generated]

If I zoom in with my mouse, the y axis does expand but the plot itself remains tiny because the y values lie in a narrow range like so:

[Chart, line chart  Description automatically generated]

I want the plot itself to cover the entire area of the square box rather just the central strip keeping the entire x-axis visible. Is there a way to zoom in the plot such that x-axis spans from -300 to 200 along with an appropriate y axis scaling, for eg. Just going from -5 to 17 between which my y-values lie?

Riddhi

From: Kathleen Biagas via visit-users <visit-users@elist.ornl.gov>
Date: Tuesday, October 20, 2020 at 8:21 PM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kathleen Biagas <notifications@github.com>, Subscribed <subscribed@noreply.github.com>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Lineout plot X axis range query (#166)

Hello Riddhi,

There isn't a way to do it directly.
You can save the curve as a vtk file, open it in VisIt, create a Mesh plot, then apply the Transform operator using the Scale option.

To save the curve as vtk, make sure the window that contains the lineout is active, then open File->Set save options
Make note of where the file is being saved, enter a filename, turn off family if desired (it appends a 4-digit number to the filename). Set type to VTK, then Save and dismiss.

[SetSaveOptions]<https://user-images.githubusercontent.com/17075318/96657906-37114480-12f8-11eb-99c2-60907e5e5def.PNG>

Once saved, open the saved file in VisIt, create a Mesh plot (you can change the color if you want).
Apply the Transform operator, set the Scale option:

[TransformOp]<https://user-images.githubusercontent.com/17075318/96658020-73dd3b80-12f8-11eb-981f-bff446bd27aa.PNG>

**Comment by biagas** [comment]
Good catch on Translate being the correct option instead of Scale. Sorry about that.

You may want to turn on 'full frame mode' if it isn't turned on already.  There are two ways to accomplish this:

You can right-click in the window with the plot to access the pop-up menu:

![RightClickView](https://user-images.githubusercontent.com/17075318/96735147-1b498500-1370-11eb-834e-9c7d1bdd938b.PNG)

Or you can open Controls->View:

![ViewWindow](https://user-images.githubusercontent.com/17075318/96735243-35836300-1370-11eb-8bf6-9369b646188c.PNG)

**Comment by markcmiller86-visit** [comment]
No problem at all!

And the Full Frame View worked wonderfully. Thanks a lot for the help. I greatly appreciate it 😊

Riddhi

From: Kathleen Biagas via visit-users <visit-users@elist.ornl.gov>
Date: Wednesday, October 21, 2020 at 10:49 AM
To: visit-dav/live-customer-response <live-customer-response@noreply.github.com>
Cc: Kathleen Biagas <notifications@github.com>, Comment <comment@noreply.github.com>, markcmiller86-visit <visit-users@ornl.gov>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Lineout plot X axis range query (#166)

Good catch on Translate being the correct option instead of Scale. Sorry about that.

You may want to turn on 'full frame mode' if it isn't turned on already. There are two ways to accomplish this:

You can right-click in the window with the plot to access the pop-up menu:

[RightClickView]<https://user-images.githubusercontent.com/17075318/96735147-1b498500-1370-11eb-834e-9c7d1bdd938b.PNG>

Or you can open Controls->View:

[ViewWindow]<https://user-images.githubusercontent.com/17075318/96735243-35836300-1370-11eb-8bf6-9369b646188c.PNG>
