### ISSUE TITLE
Ignore zones that are duplicated at the domain boundaries

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#173]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Gensis Rosado-Martinez is using a python script to load silo files into visit and query the zones. As a check, she exports ZoneId of the dataset to csv and examines the output. She finds that some zones are appearing in multiple domains. She believes these are ghost zones. She wants to turn "turn off" zones that are duplicated at the domain boundaries.

Possibly related to [3186](https://github.com/visit-dav/visit/issues/3186)

**Comment by rusu24edward** [comment]
Further clarification: The user is writing out data to numpy for training ML. The zones are duplicated in the numpy output, which is bad for training.

**Comment by markcmiller86** [comment]
Hmmm...how does she know the zones are duplicated? Looking at `ZoneId` alone I don't think is enough. **Global** zone-ids would be sufficient. Otherwise, I think each domain numbers its zones 0...numZones-1.

Next, would the `Inverse Ghost Zones` operator help here? Thats not the best name of the operator as it has controls for many types of ghost zones and is generally designed to output *only* ghosts of various types. But, it could be used to help detect if a zone is ghost or not in the python code. Another option might be a Python filter where she could more easily access vtkDataArrays for ghost data and use that to inform her logic.

**Comment by rusu24edward** [comment]
I've requested the extraction script from the user, so we'll see if Global zone id is being used. I think `vtk_to_numpy` might provide the path forward here.

We did look into Inverse Ghost Zones operator, although not to identify if the zones are ghost because I assumed they were.

**Comment by rusu24edward** [comment]
> Looking at `ZoneId` alone I don't think is enough. **Global** zone-ids would be sufficient.

The user is using the global zone id. The Ghost Zone operator is a good idea. Do you know how one might use a python filter to determine if a zone is ghost?

**Comment by rusu24edward** [comment]
Directed user to use `GetCellData()->GetArray("avtGhostZones")`, which I believe will work here.

**Comment by rusu24edward** [comment]
Pointed user to [numpy support module](https://github.com/Kitware/VTK/blob/master/Wrapping/Python/vtkmodules/util/numpy_support.py) for reference.

**Comment by brugger1** [comment]
The user sent me her scripts as well and I took a look at them. She is using a Python Query to output the csv file. In the case of zones, the script can be modified to use  "avtGhostZones" to check if the zone is a ghost zone.

The code fragment from her script with the modification is:

    def export_csv(self, data, num_elem, file_name):
        names = [n for n in self.input_var_names if data.HasArray(n) == 1]
        if len(names) == 0:
            return

        with open('%s/%s.csv' % (self.outdir, file_name), 'w') as out:
            out.write(','.join(names) + '\n')

            ghost = data.GetArray("avtGhostZones")
            arrays = [data.GetArray(n) for n in names]

            for i in xrange(num_elem):
                if (ghost.GetTuple1(i) == 0):
                    out.write(','.join(str(a.GetTuple1(i)) for a in arrays) + '\n')

Note that this won't work for nodal variables, even if "avtGhostZones" is replaced with "avtGhostNodes", since that would not output any duplicated nodes and you actually want to output each duplicated node once.
