### ISSUE TITLE
Centroid zero with projected mesh.

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#181]
I had a user Project a 3d mesh to 2d and he now wants to calculate the centroid, but it is coming up zero. Here is the user's e-mail.

Thanks, Eric. The Transform operator followed by the Project operator to create a projection on a coordinate plane can be used in lieu of a projection to the viewing plane. 

As a follow up, I noticed that the query results for the projection produce results that are not quite intuitive. For example, the 2D area is twice the expected value and is equal to the 3D surface area; it’s as though the projection has a front and back “face” and is infinitely thin (i.e., the volume query returns 0.0). Since the volume query returns 0.0, the centroid is also returned as a 0.0 value. 

We would like to calculate the centroid of the projection. Is there a workaround that you can think of that would get around the zero volume limitation (which I’m guessing is the cause of the zero centroid result)?

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by biagas** [comment]
In regards to the 2D area, the Project operator doesn't remove cells, in the simple case of XY Cartesian plane, it simply sets all the z-coordinates to 0. The 2D area query calculates the area on all the cells given, so that's why it is returning incorrect results in this instance.

For Centroid query, I see a couple of problems: First, the logic to determine whether to use volume or area in the calculation I believe is wrong: It tests topological dimension is 3 instead of testing spatial dimension.  Second, when I modified the query to test spatial dim, so that is uses area in its calculation, the calculated area for every cell is 0.  This is due to use of the verdict area metric, which only calculates area for triangles and quads, but it is receiving hexes (in the case of rect3d projected).

**Comment by biagas** [comment]
Submitted [ticket](https://github.com/visit-dav/visit/issues/5408) and closing this.
