### ISSUE TITLE
GitHub discussions

### ISSUE THREAD

**Issue by dealmeidavf** [visit-dav/live-customer-response#200]
Hi, there is a new feature in GitHub for discussions. You may be interested in enabling it.
Just a thought.
Thanks.

**Comment by markcmiller86** [comment]
Thanks for the suggestion. Can you maybe elaborate on why? What is the benefit or value added over issue conversations?

As currently used, our `live-customer-respons` is an *issues-only* repo (e.g. no code) (admittedly isn't the best name...mayb we should change it) that is intentionally integrated with our `visit-users` email list. That is because we are encouraging our users to use GitHub for interacting with us on such things. However, those that prefer email can still do so.

It is for handling issues people encounter in the *use* of VisIt (building it with `build_visit`, running it in client/server mode, using subset selection, etc., etc.). The issues may be outright bugs or they may just be minsunderstanding in how to use the VisIt eco-system. Outright bugs we'll move to our code [issue tracker](https://github.com/visit-dav/visit/issues).

[This ref](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-conversations-on-github) indicates...

>On your team's page, you can use team discussions for conversations that **span across projects or repositories and don't belong in a specific issue or pull request**.

which isn't really the intention `live-customer-response`.

**Comment by dealmeidavf** [comment]
Your intended use of GitHub issues works well in a separate repo. The Discussion feature allows you to setup categories; which helps organizing the topics for discussion. There is also an *answer*  event for Q&A which helps identify which posting answered a question. Some examples [here](https://github.com/idaholab/moose/discussions). 

Your current setting works well; thanks for the user support.

--
Valmor
