### ISSUE TITLE
Subset gives error on Exodus parallel output

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#235]
I'm using VisIt 3.1.3 in client-server to postprocess Exodus output from Sierra Presto v4.56. Presto can write its output either as a single file, or as multiple output files, one for each core used. When I subset > ElementBlock with the single Exodus output file, VisIt works fine; but when I subset the multiple parallel output files, VisIt throws the error "Pseudocolor:  ();
viewer.exe: The pipeline object is being used improperly." Interestingly, only certain blocks and certain combinations of blocks cause the error. This error occurs when I run VisIt in serial. In parallel, VisIt just hangs.
I created a simple test problem, which manifests the problem with one exception. In my actual simulation, some blocks turned off singly cause the error, and some blocks turned off in pairs or more cause the error. In my test problem I can turn each block off singly and no error is given. If I turn some of them off in pairs (or more), the error occurs, but not all pairs cause the error.
The Exodus output from my simple problem totals about 13 MB compressed. Let me know if you'd like me to send them to you.
Thanks,
Keith

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Keith,

Yes, the simple test problem would be very helpful in diagnosing the problem. You can e-mail it to me at brugger1@llnl.gov. Can you add the extension ".abcxyz" to the file so that our firewall doesn't strip the attachment.

Thanks,

Eric

**Comment by markcmiller86-visit** [comment]
Hi,

This looks similar to a  behavior I noticed a while ago when due to the partitioning, not all element blocks / vertex sets are represented in  all files. In my case, I had to modify the I/O in my code to make sure that the list of element blocks and cell sets in each file be the same, even though some are empty in some files. Does that make sense?

Regards,
Blaise

> On Mar 15, 2021, at 12:34 PM, Eric Brugger via visit-users ***@***.***> wrote:
> 
> 
> Hi Keith,
> 
> Yes, the simple test problem would be very helpful in diagnosing the problem. You can e-mail it to me at ***@***.*** Can you add the extension ".abcxyz" to the file so that our firewall doesn't strip the attachment.
> 
> Thanks,
> 
> Eric
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> --
> VisIt Users Wiki: http://visitusers.org/
> Frequently Asked Questions for VisIt: https://wci.llnl.gov/simulation/computer-codes/visit/FAQ.html
> To Unsubscribe: send a blank email to ***@***.***
> More Options: https://elist.ornl.gov/mailman/listinfo/visit-users

-- 
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin

**Comment by markcmiller86** [comment]
In response to Blaise’ question, yes, I think so. See below a short email excchange with Greg Sjaardema on this issue with Parallel Exodus files...


"Miller, Mark C." wrote:

Hi Rick,

Here is Greg's response...

"Sjaardema, Gregory D" wrote:

They must all have the same element block count and the ids (and names) of the element blocks must be consistent.
..Greg

Now, this is a *convention* requirement in the data producer. A decent question is how big is the Exodus-based software eco-system out there that is designed around this convention? It maybe only that VisIt and ParaView are the primary consumers of parallel Exodus in which case it might be worth considering a change in conventions. I think Nemesis (the parallel wrapper for Exodus) also enforces this convention. OTOH, how problematic is it for CTH code to produce data that adheres to this convention? I'd find it hard to believe it would represent undue burden on the data producer to meet this convention.

My inclination is to ask CTH team to adhere to the convention in the data the produce. In addition, as per my other comment regarding agreement across files about which block has a given block Id is also a potential issue that *cannot* be solved simply by knowing maximum block count. The data producer *must* indicate global element-block ids to get parallel vis to work correctly.

Finally, even if/when CTH is 'fixed' to adhere to this convention, I still think VisIt has a problem when changing timesteps that we may need to correct (treat all dbs as time varying pref would correct that issue now).

Mark



--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

From: "Miller, Mark C." ***@***.***>
Date: Thursday, February 9, 2017 at 11:08 AM
To: "Sjaardema, Gregory D" ***@***.***>
Subject: [EXTERNAL] Proper way to handele num_elm_blk in parallel

Hi Greg,

Quick question for you. If a parallel code uses file-per-processor Exodus output, is there any requirement that for the code to have produced a 'valid' ensemble of Exodus files, all ranks must agree on the element block count?

I have data from ARL where different ranks output different element block counts. Its not even clear to me if element block id say visit-dav/visit#12110 means the same thing across all files.

Mark


--
Mark C. Miller, LLNL

"In the end, we will remember not the words of
our enemies but the silence of our friends" - MLK

**Comment by markcmiller86-visit** [comment]
Honestly, I think that the _right_ solution is to go away with file based domain decomposition, especially now that exodus supports partial read / write and MPIIO using pnetcdf or hdf5. But if somebody is going to do multiple files IO, it makes sense to have consistent headers across all files (i.e. same number of sets, ID etc).

Regards,,
Blaise


On Mar 15, 2021, at 4:59 PM, Mark C. Miller via visit-users ***@***.******@***.***>> wrote:


In response to Blaise’ question, yes, I think so. See below a short email excchange with Greg Sjaardema on this issue with Parallel Exodus files...


"Miller, Mark C." wrote:

Hi Rick,

Here is Greg's response...

"Sjaardema, Gregory D" wrote:

They must all have the same element block count and the ids (and names) of the element blocks must be consistent.
..Greg

Now, this is a *convention* requirement in the data producer. A decent question is how big is the Exodus-based software eco-system out there that is designed around this convention? It maybe only that VisIt and ParaView are the primary consumers of parallel Exodus in which case it might be worth considering a change in conventions. I think Nemesis (the parallel wrapper for Exodus) also enforces this convention. OTOH, how problematic is it for CTH code to produce data that adheres to this convention? I'd find it hard to believe it would represent undue burden on the data producer to meet this convention.

My inclination is to ask CTH team to adhere to the convention in the data the produce. In addition, as per my other comment regarding agreement across files about which block has a given block Id is also a potential issue that *cannot* be solved simply by knowing maximum block count. The data producer *must* indicate global element-block ids to get parallel vis to work correctly.

Finally, even if/when CTH is 'fixed' to adhere to this convention, I still think VisIt has a problem when changing timesteps that we may need to correct (treat all dbs as time varying pref would correct that issue now).

Mark



--
"A supercomputer is a device for turning compute-bound problems into I/O-bound problems”

From: "Miller, Mark C." ***@***.***>
Date: Thursday, February 9, 2017 at 11:08 AM
To: "Sjaardema, Gregory D" ***@***.***>
Subject: [EXTERNAL] Proper way to handele num_elm_blk in parallel

Hi Greg,

Quick question for you. If a parallel code uses file-per-processor Exodus output, is there any requirement that for the code to have produced a 'valid' ensemble of Exodus files, all ranks must agree on the element block count?

I have data from ARL where different ranks output different element block counts. Its not even clear to me if element block id say visit-dav/visit#12110 means the same thing across all files.

Mark


--
Mark C. Miller, LLNL

"In the end, we will remember not the words of
our enemies but the silence of our friends" - MLK

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvisit-dav%2Flive-customer-response%2Fissues%2F235%23issuecomment-799782194&data=04%7C01%7Cbourdin%40lsu.edu%7C3370272b6ab14132cbe808d8e7fd9088%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637514423528865918%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=l4RpB5gJKE58HLiaE1HYP0Lv1ncx6Rcgynz%2BTJHThbg%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOLAYZG6KPSS2SPI3VW3XZTTDZ7KTANCNFSM4ZG74FLQ&data=04%7C01%7Cbourdin%40lsu.edu%7C3370272b6ab14132cbe808d8e7fd9088%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637514423528865918%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4ZF6fszo7bHP4tnaE%2ByA%2FCfeuVXnvqSiJnNXTzAWQHc%3D&reserved=0>.

--
VisIt Users Wiki: http://visitusers.org/
Frequently Asked Questions for VisIt: https://wci.llnl.gov/simulation/computer-codes/visit/FAQ.html
To Unsubscribe: send a blank email to ***@***.******@***.***>
More Options: https://elist.ornl.gov/mailman/listinfo/visit-users

--
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin

**Comment by brugger1** [comment]
Keith,

I've looked at the file and I believe the issue is what Blaise mentioned. It has to do with some of the element blocks being missing in some of the files. The problem exists even if only a single file is opened, so treating the database as time varying would not fix the problem.

Here is the element block information for the first file.

There are 9 element blocks across all the files. The first file only has 4 element blocks populated.

 eb_status = 0, 0, 0, 1, 1, 0, 1, 1, 0 ;

 eb_prop1 = 1, 2, 3, 4, 5, 6, 7, 8, 9 ;

 eb_names =
  "lr",
  "lm",
  "ll",
  "mr",
  "mm",
  "ml",
  "ur",
  "um",
  "ul" ;

When VisIt displays the element block names it is combining the eb_names with the eb_prop1, so the names are lr_1, lm_2, ll_3, mr_4, ...

I believe adding information to the file for all 9 element blocks and having some of them have 0 elements, as Blaise mentioned, would solve the problem.

It seems like this could still potentially be handled in VisIt, since all the element blocks are listed in the "metadata" in all the files, it's just that some don't have any data. Perhaps, if a block wasn't present, we just returned a NULL block for it, so that the processing in VisIt downstream would be happy. I suspect we do something similar with other readers. @markcmiller86 thoughts?

**Comment by markcmiller86** [comment]
> It seems like this could still potentially be handled in VisIt, since all the element blocks are listed in the "metadata" in all the files, it's just that some don't have any data. Perhaps, if a block wasn't present, we just returned a NULL block for it, so that the processing in VisIt downstream would be happy. I suspect we do something similar with other readers. @markcmiller86 thoughts?

If you are saying that each file does indeed know about *all* blocks, that they are all in the same *order* and all have the same *names* and that the *only* difference among them is that some blocks are effectively *empty*, then yes, we should fix this behavior in Exodus plugin. If there are other differences in eb configuration among the file, that implies the need for global communication among the files during `PopulateDatabaseMetaData()` which is best to avoid (and which is similar to the challenge we had with Mili and solved by adding a new function to Mili that effectively does that at database close time in the data producer -- maybe adding (or creating) an Exodus function that does something similar to that would solve these parallel Exodus problems?

**Comment by brugger1** [comment]
I submitted the issue https://github.com/visit-dav/visit/issues/5720 to track this bug.
