### ISSUE TITLE
Adding frames around zones in visualization

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#241]
Hi,

Is there a way to have a lines on the pseudocolor visualization, showing the border between zones?

In the attached figure, I have 5 material zones, but I cannot see the borders between them.

Regards,

Juan

![Screen Shot 2021-04-07 at 1 30 35 AM](https://user-images.githubusercontent.com/1102718/113884014-80a0ff00-9773-11eb-8a8d-ae34d379c6d0.png)

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Juan,

You would need to have some way to identify the different materials. If the different materials are identified by different ranges in a variable, you could add a Contour plot and set the contour levels to be the values where the materials changed. For example, if the materials could be identified by density and the densities for the materials were in the ranges:

Material 1 1.5 - 1.8
Material 2 1.8 - 2.1
Material 3 2.1 - 2.2
Material 4 2.2 - 2.8
Material 5 2.8 - 3.1

then adding a Contour plot and setting the contour levels to 1.8, 2.1, 2.2 and 2.8 would produce lines at the material interfaces.

If that doesn't apply to your situation, could you describe how the materials could be identified?

Eric

**Comment by markcmiller86-visit** [comment]
Hi Eric,

Thanks for your response.  Each material is in a different zone, as seen
here:

![SubsetList](https://user-images.githubusercontent.com/1102718/113903735-252c3c80-9786-11eb-8dbe-8d5a2f1d4ce9.png)

Regards,

Juan

**Comment by brugger1** [comment]
Hi Juan,

In this case you can add a Subset plot of Zones (Add->Subset->Zones).

This will color the Zones a solid color. To display a border around each Zone, bring up the Subset attributes and turn on "Wireframe". If you want all the borders the same color, change the subset color to a single color.

![SubsetAttributes](https://user-images.githubusercontent.com/1102718/113904503-fa8eb380-9786-11eb-8981-fcfa97c9ddee.png)

**Comment by markcmiller86-visit** [comment]
Hi Eric,

Thanks for your help.  The solid colors work, but the wireframe option
colors each tetrahedral element and not just the border.

![SubsetPlot](https://user-images.githubusercontent.com/1102718/113909647-c4543280-978c-11eb-9c5e-1da0ec8049c8.png)

Regards,

Juan

**Comment by brugger1** [comment]
Hi Juan,

I suspect that this is being caused by the tetrahedral connectivity treating each element as an independent tetrahedron. VisIt determines the exterior boundary using the connectivity. For example, suppose you have 2 triangles that form a quad, sharing a diagonal of the quad.

`2-4`
`|\|`
`1-3`

If they were 2 independent triangles then the connectivity would be

Triangle 1 - 1 2 3
Triangle 2 - 4 5 6

with vertex 4 duplicating vertex 2 and vertex 5 duplicating vertex 3 and vertex 6 being vertex 4

and you would see 2 triangles.

If they were 2 connected triangles then the connectivity would be

Triangle 1 - 1 2 3
Triangle 2 - 2 3 4

and you would see the outline of the quad since it would recognize that edge 2 - 3 was shared and therefore interior to the block.

**Comment by markcmiller86-visit** [comment]
Hi Eric,

I did not see the problem for my exodus input file.  I am going to write a
python scripts which orients the surface normals of the tetrahedra pointing
out by changing the node ordering.

Regards,

Juan

**Comment by markcmiller86-visit** [comment]
Hi Juan,

Yes, that is the right path forward. I wanted to find a nice reference on how to order the nodes and couldn’t find anything quickly, but it is a node ordering issue. Sorting the nodes is definitely incorrect. The nodes for tetrahedra on opposite sides of a face need to be in the opposite order. Using the first 2 tetrahedra as an example and assuming the first tetrahedron was oriented correctly, then they would be:

1 2 3 4
3 2 1 172

Eric

**Comment by markcmiller86** [comment]
Before you go changing connectivity, try going to [global prefs](https://visit-sphinx-github-user-manual.readthedocs.io/en/develop/gui_manual/Preferences/Preferences_Window.html) and checking the box there `Automatically remove duplicate nodes from fully disconnected unstructured grids` and see if that provides any relief.

![Screen Shot 2021-04-07 at 2 09 09 PM](https://user-images.githubusercontent.com/5720676/113934604-d513a100-97aa-11eb-9343-499623fe7ba3.png)

**Comment by markcmiller86-visit** [comment]
![Screen Shot](https://user-images.githubusercontent.com/1102718/114044482-215af180-983c-11eb-8ea9-cc8695a9b2fd.png)

Hi Eric,

I was able to fix the issue in the output of my program with tetrahedra.  I
just needed to ensure that for these node triangle orderings, that the
cross product pointed away from the fourth node.
1 2 4
2 3 4
1 4 3
1 3 2

So the desired ordering will always be:
1 2 4 3

For a sorted tetrahedron list, it is necessary to form 3 vectors from their
coordinate positions:
v21, v32, v43

if dot(cross(v32,v43),  v21) has the "wrong" sign, then swap nodes 3 and 4.

So I have my program use this ordering, when writing output visualization
files, or the user requests the ordering in an FE aware style.

For 2d meshes, I probably need to make sure all the triangles face up.

Thanks for all of your help in figuring this out.

Regards,

Juan

**Comment by brugger1** [comment]
Hi Juan,

Glad you got it working. Thanks for reporting back with your solution.

Eric

**Comment by markcmiller86-visit** [comment]
Hi Mark,

Sorry I missed your email, before I fixed the tetrahedra node ordering on
output from my software.  It is probably good I do it anyway, because it
seems many software applications have this requirement.

From your figure, how does "Automatically create vector magnitude
expressions" work?  Do I need to name the scalar fields in my Tecplot file,
if I want them combined into a vector?  Or do I still need to create the
vector expression first?

Regards,

Juan

**Comment by markcmiller86** [comment]
> From your figure, how does "Automatically create vector magnitude expressions" work?

Its mainly transparent to you. If I understood the situation correctly, you had an input mesh consisting of a collection of tets where each tet was wholly disconnected (e.g. did not share any nodes) from every other tet. That is a *fully disconnected* ucd mesh and VisIt can do a little work to connect it for you if that pref is set. I do think the nodes of each tet *must* use the bit-for-bit identical coordinate values. If they don't pass `==` test, it may foil the connection algorithm.

Zonal fields (e.g. zone-centered) should require no special work to handle correctly.  As for node-centered fields, hmmm..., I can't recall if after eliminating duplicate nodes, we handle re-mapping nodal field data. I think we do so that should be transparent as well.

Do I need to name the scalar fields in my Tecplot file, if I want them combined into a vector? Or do I still need to create the vector expression first?

I am not sure I follow this question but I don't think you should need to do anything different than you would if you had written a fully connected mesh instead. 

I was mainly suggesting this as a quick work-around to help you save the effort of writing the code to fully connect the mesh in the data producer before writing it to the file. If you've already done that though, that is probably better to just continuing using and forget about my suggestion here.

**Comment by markcmiller86-visit** [comment]
Hi,

Thanks for your response.  I was interested in what is required to
"Automatically create vector magnitude expressions".  I am supposing I will
still need to create the vector expression, and then its magnitude
expression will be created for me.  This was unrelated to the original
topic.

On the topic of disconnected mesh nodes:  In my case, VisIt was not able to
see the tetrahedra were connected, because the element nodes were not
listed in the proper orientation.  So the node indexes were correct, but
the faces needed to point outward.

Regards,

Juan
