### ISSUE TITLE
Material plots from Hydra bug in 3.1.4

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#244]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I can no longer make material plots from Hydra using VisIt. Every time I try this I get an error in the compute engine. This happens when I run on rztopaz or rztrona. I also get same error when I run on my Mac and remote login to rztopaz.
 
These plots were working in early February on these systems.
 
Oggie Jones

**Comment by brugger1** [comment]
Hi Oggie,

Jay Salmonson reported the same issue a week ago. I looked into it and found that the domain boundary information that specifies how domains connect to each other has an issue and is causing VisIt to crash. Jay said he reported the issue to the hydra developers (this was last Friday 4/9). I haven’t heard any news since. I can modify our reader to work around the issue, but I’d like to hear some feedback that the change was intentional before modifying our reader.

Eric

**Comment by markcmiller86-visit** [comment]
Ok, thanks.

From: Eric Brugger via visit-users ***@***.***>
Reply-To: visit-dav/live-customer-response ***@***.***>, VisIt software users community ***@***.***>
Date: Thursday, April 15, 2021 at 11:22 AM
To: visit-dav/live-customer-response ***@***.***>
Cc: Eric Brugger ***@***.***>, Subscribed ***@***.***>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Material plots from Hydra bug in 3.1.4 (#244)


Hi Oggie,

Jay Salmonson reported the same issue a week ago. I looked into it and found that the domain boundary information that specifies how domains connect to each other has an issue and is causing VisIt to crash. Jay said he reported the issue to the hydra developers (this was last Friday 4/9). I haven’t heard any news since. I can modify our reader to work around the issue, but I’d like to hear some feedback that the change was intentional before modifying our reader.

Eric

**Comment by brugger1** [comment]
Hi Oggie,

I just sent an e-mail to one of the Hydra developers.

Eric

**Comment by brugger1** [comment]
Hi Oggie,

I just heard back from one of the Hydra developers and he found the problem in Hydra.

Eric
