### ISSUE TITLE
Visit error on Trinity

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#246]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi,
 
I’m trying to run visit on Trinity but running into an error. The file I’m executing is /usr/projects/views/visit/bin/visit. It’s giving me the following error:
 
/usr/projects/views/visit/2.13.3/linux-x86_64/bin/gui: error while loading shared libraries: libicuil8n.so.52.1: cannot open shared object file: No such file or directory
 
Could there be any module issues or pathing issues?
 
Yuan

**Comment by rusu24edward** [comment]
Hi Yan,

I believe your issue is similar to one we had previously encountered on Trinity systems (see [here](https://github.com/visit-dav/visit/issues/5201) for more details). It appears that the older versions of libraries that Visit uses got upgraded. We rebuilt and tested version 3.1.1 using the newer dependencies, and that worked. Can you try running that version and let me know if that works for you?

Eddie

**Comment by markcmiller86-visit** [comment]
Eddie,

There are no executables in the 3.1.1 folder. The only folder with an executable is in the main bin folder which seems to point to v2.13.2. Would someone be able to rebuild and replace the executable in the bin folder with the updated version?

Yuan

From: Edward Rusu via visit-users ***@***.***>
Sent: Thursday, April 15, 2021 4:39 PM
To: visit-dav/live-customer-response ***@***.***>
Cc: Edward Rusu ***@***.***>; Subscribed ***@***.***>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Visit error on Trinity (#246)


Hi Yan,

I believe your issue is similar to one we had previously encountered on Trinity systems (see here<https://urldefense.us/v3/__https:/github.com/visit-dav/visit/issues/5201__;!!G2kpM7uM-TzIFchu!haxacV4Cpc_i6Hnq8zEx_upguTKaEVNbSIELzAAtBwwK8baepBDwi57OqJKqRfI$> for more details). It appears that the older versions of libraries that Visit uses got upgraded. We rebuilt and tested version 3.1.1 using the newer dependencies, and that worked. Can you try running that version and let me know if that works for you?

Eddie

**Comment by brugger1** [comment]
Hi Yuan,

There should be other versions installed on trinity. Are you running directly on the login node?

Can you try “/usr/projects/views/visit/bin/visit -v 3.1.1”?

Thanks,

Eric

**Comment by brugger1** [comment]
Eric,

Using the command you listed worked. There are other versions in the folder but 3.1.1 seems to be the newest.

Thanks for the help,
Yuan
