### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by mahdadt** [visit-dav/live-customer-response#250]
Hello,

I have been trying to install or build VisIt on our university HPC system and it is not working. After installation was unsuccessful due to some problem with the system's python libraries I decided to build it using the build script provided. But I got an error in the building process. I attached my log so you can help me. 

Thank you,
Mahdad
[build_visit3_1_4_log.txt](https://github.com/visit-dav/live-customer-response/files/6361921/build_visit3_1_4_log.txt)

**Comment by biagas** [comment]
Hello Mahdad, I apologize for the delay in responding.

Your error message is related to python 3 ( No module named '_ctypes').
We encountered this error before on an old RHEL 6 system (See ticket [4758](https://github.com/visit-dav/visit/issues/4758)).
Since you are building 3.1.4, python3 is only required for building our sphinx documentation, so you can work around the error by adding '--no-sphinx' to your build_visit3_1_4 invocation.

HTH

Kathleen

**Comment by markcmiller86-visit** [comment]
Hello Kathleen,

Thank you for your help. I tried the --no-sphinx and it worked.

Thanks,
Mahdad
Mahdad Talebpour
PhD Candidate, Chemical, Biochemical, and Environmental Engineering
UMBC
TRC 104
1000 Hilltop Circle
Baltimore, MD 21250
