### ISSUE TITLE
Exodus from VisIt?

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#254]
Hello,
I'm using VisIt to post-process ALE3D output, and I need to convert it to Exodus, which isn't an option in File > Export Database...  Does anyone have any suggestions? And can I request an enhancement for VisIt?
Thanks,
Keith

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by markcmiller86** [comment]
Hmmm...already responded to an LLNL user that made this request on behalf of Keith. Here is my response...


> Hmm....I did write a python script to convert some silo data to Exodus. It uses Silo’s and Exodus’ native python interfaces to do it.
 
> VisIt can read Silo but I don’t think it can write Exodus. We should probably add a writer for Exodus.
 
> Typically, Exodus does not support mixed materials. That isn’t quite true. I’ve seen Exodus files with mixed materials. But, they represent specific conventions in the use of Exodus for that purpose based on Alegra and CTH codes at Sandia. Baring those conventions, a problem is to take mixed material hexes in Silo and create clean material tets in Exodus. We’d need material interface reconstruction code for that and the only place that exists is in VisIt. Hmmm...
 
> If we read the Silo data into VisIt and do a FORCED MIR plot and export of it, we could get out *clean* material zones (e.g. a ucd mesh with hexes, wedges, pyramids and tets but which are all clean in material). Then, we could write python code to read this, convert non-tet shapes to tet and write to Exodus.
 
> When are you thinking you need to have a solution by?

**Comment by markcmiller86-visit** [comment]
On Apr 27, 2021, at 6:40 PM, Mark C. Miller via visit-users ***@***.******@***.***>> wrote:



Hmmm...already responded to an LLNL user that made this request on behalf of Keith. Here is my response...

Hmm....I did write a python script to convert some silo data to Exodus. It uses Silo’s and Exodus’ native python interfaces to do it.

VisIt can read Silo but I don’t think it can write Exodus. We should probably add a writer for Exodus.

Typically, Exodus does not support mixed materials. That isn’t quite true. I’ve seen Exodus files with mixed materials. But, they represent specific conventions in the use of Exodus for that purpose based on Alegra and CTH codes at Sandia. Baring those conventions, a problem is to take mixed material hexes in Silo and create clean material tets in Exodus. We’d need material interface reconstruction code for that and the only place that exists is in VisIt. Hmmm...

I am not quite sure I agree with this statement. Exodus supports object properties and distribution factors that are a natural location to store material properties. However, it is correct that neither of these are explicitly limited to be used to store materials properties.

If some work is going to be done on the exodus I/O, would it make sense to leverage the exodus library which has been actively developed in the past, instead of extending the custom netcdf-based reader?

Regards,
Blaise



If we read the Silo data into VisIt and do a FORCED MIR plot and export of it, we could get out clean material zones (e.g. a ucd mesh with hexes, wedges, pyramids and tets but which are all clean in material). Then, we could write python code to read this, convert non-tet shapes to tet and write to Exodus.

When are you thinking you need to have a solution by?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvisit-dav%2Flive-customer-response%2Fissues%2F254%23issuecomment-828027092&data=04%7C01%7Cbourdin%40lsu.edu%7Cdd2a8fbaa77449e5268f08d909d5db66%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637551636385385805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kkIeHpocT4Y5frk3YTLy5l%2B%2BvFn0QyZUXAVuVc%2B2xNA%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOLAYZCI4JDCBUQM7R3DE7TTK5DPBANCNFSM43V6MGNQ&data=04%7C01%7Cbourdin%40lsu.edu%7Cdd2a8fbaa77449e5268f08d909d5db66%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637551636385385805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qNiI9aC8rxApwsleP3eBtqcJtsNY%2B4eMtmRV67iDuDo%3D&reserved=0>.

--
VisIt Users Wiki: http://visitusers.org/
Frequently Asked Questions for VisIt: https://wci.llnl.gov/simulation/computer-codes/visit/FAQ.html
To Unsubscribe: send a blank email to ***@***.******@***.***>
More Options: https://elist.ornl.gov/mailman/listinfo/visit-users

--
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin
