### ISSUE TITLE
Approval for using visit at SNL

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#273]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Dear All,
 
I was interested to use Visit for visualization of data I have been generating.
However, I have been requested by my employer Sandia national Lab. (SNL) to provide
a document or an approval web site page that your software can be used by SNL.
I therefore would like to kindly ask you if you have any document that states the free use
of your software or if you can guide me to the page, if there is one, that states
the approval of free use by any governmental or private institutions. I greatly
appreciate your help.
Thank you.
 
With Regards,
Wond Mengesha
Sandia National Laboratories.

**Comment by rusu24edward** [comment]
Dear Wond Mengesha,

I'm surprised you were asked you for this because Visit is used at Sandia regularly... Anyways, [here is a link](https://github.com/visit-dav/visit) to our open-source repository. You can find the LICENSE file there, which states the stipulations for _redistribution_ of Visit, and because Visit is open-source, it can be _used_ by anyone without restriction. Here is [also a link to our website](https://visit-dav.github.io/visit-website/), in case that is helpful too for your documentation.

Eddie

**Comment by markcmiller86-visit** [comment]
Dear Eddie,
Thank you for the quick response. It was a surprise for me too.
Thanks for the link you gave me.
Regards,
Wond

From: Edward Rusu via visit-users ***@***.***>
Sent: Tuesday, May 25, 2021 11:13 AM
To: visit-dav/live-customer-response ***@***.***>
Cc: Edward Rusu ***@***.***>; Subscribed ***@***.***>
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Approval for using visit at SNL (#273)


Dear Wond Mengesha,

I'm surprised you were asked you for this because Visit is used at Sandia regularly... Anyways, here is a link<https://github.com/visit-dav/visit> to our open-source repository. You can find the LICENSE file there, which states the stipulations for redistribution of Visit, and because Visit is open-source, it can be used by anyone without restriction. Here is also a link to our website<https://visit-dav.github.io/visit-website/>, in case that is helpful too for your documentation.

Eddie
