### ISSUE TITLE
LLLNL CZ machines from mac

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#277]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hi—I’ve long been using Visit (currently 3.1.4) on my Mac (currently OS 10.15.7) to connect to LLNL’s rzrtopaz. I just started working on quartz for the first time in a long time, and when I tell VisIt that that’s where I want to go, instead of giving me a window to enter my password, it hangs. I’ve found that the RZ machines rztopaz and rzgenie I can reach, but the CZ machines quart and syrah both cause VisIt to hang. Any idea what’s up?
 
Thanks,
Chris

**Comment by brugger1** [comment]
I resolved this off line with the user directly. It turns out that when when VisIt ssh-ed to quartz, ssh came back with:

The authenticity of host 'quartz.llnl.gov (134.9.54.13)' can't be established.
ECDSA key fingerprint is SHA256:XXXXX...XXXXX
Are you sure you want to continue connecting (yes/no/[fingerprint])? 

,which VisIt didn't respond to and didn't show the user.

I had the user ssh from his mac to quartz.llnl.gov and then answer "yes". After that VisIt worked properly because the situation was no longer happening. The user could have also changed the host name to just "quartz" in the host profile, since he normally ssh-es to just "quartz".
