### ISSUE TITLE
Is it possible to visualize in spherical coordinate system?

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#41]
> Also, is it possible to visualise in spherical coordinate system? When transforming coordinates, the reference system (the one one the bottom-left corner) stays x ,y, z.
> 
> Thank you.
> 
> Kind regards,
> Silvia

**From Mahesh Natarajan:
VisIt docs https://visit-sphinx-github-user-manual.readthedocs.io/en/latest/Operators/OperatorTypes/Transform_operator.html tells

"Ultimately, when a plot is rendered in the visualization window, its coordinates must be specified in terms of Cartesian coordinates due to the implementation of graphics hardware."

You could use the clip and slice operators to make plots like the one attached, but visualizing in spherical coordinates, I am not sure. Others might have some suggestions.**

![live-customer-response-41a](https://user-images.githubusercontent.com/1102718/80012092-a3aea200-8481-11ea-80a9-4b6b0ae72d46.png)

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by griffin28** [comment]
Again, Thanks Mahesh for the helpful response!

**Comment by brugger1** [comment]
Hi Silvia,

If the coordinates in your data are r, theta, phi  then you can transform them to look like a sphere using

x = r * sin(theta) * cos(phi)
y = r * sin(theta) * sin(phi)
z = r * cos(theta)

You can do this with a combination of expressions and the Displace operator.

First define:

r = coord(mesh)[0]
theta = coord(mesh)[1]
phi = coord(mesh)[2]
x = r * sin(theta) * cos(phi)
y = r * sin(theta) * sin(phi)
z = r * cos(theta)
sphere_displacement = {x - r, y - theta, z - phi}

in the "Expression" window, making sure to specify the "sphere_displacement" "Type" as "Vector mesh variable"

You can then create you plot, add the Displace operator (Operators->Transforms->Displace), displacing by "sphere_displacement". I'm using the "sphere_displacement" to set the coordinates to the x, y, and z coordinates I defined in the expressions. Since the Displace operator adds a vector to each coordinate, rather than setting it to a vector, I'm subtracting the {r, theta, phi} in the displacement, to set the coordinates to all zero and adding in the new {x, y, z}.

I did a similar set of expressions using the "rect3d.silo" sample data file and transformed a cube going from 0 -> 1 in each direction to the following image.

![live-customer-response-41](https://user-images.githubusercontent.com/1102718/80011826-3ef34780-8481-11ea-9ca7-e59076434955.png)

**Comment by markcmiller86** [comment]
@brugger1 this is awesome! We need to put this in the manual somehow.

**Comment by griffin28** [comment]
I agree @markcmiller86 ...I added a [ticket](https://github.com/visit-dav/visit/issues/4644) for adding the documentation. I will do it if time permits after I add documentation for building with masonry.

**Comment by markcmiller86** [comment]
@brugger1 any chance you have a session file from this lying around you can attach?

**Comment by markcmiller86-visit** [comment]
Hi Eric,

Thank you very much. Your explanation is extremely clear and useful.

In my case, the coordinates in my data are  x, y, z. But I assume I can go inversely? So I would use

r = sqrt(x*x+y*y+z*z)
theta = arctan(sqrt(x*x+y*y)/z)
phi = acrtan (y/x)

and my sphere displacement would be

sphere_displacement = {r -x, y - theta, z - phi}.

Thank you.

Kind regards,
Silvia



________________________________

**Comment by griffin28** [comment]
@brugger shouldn't the Transform operator with the attributes shown in the attachment do the same thing?

<img width="625" alt="Screen Shot 2020-04-23 at 5 18 04 PM" src="https://user-images.githubusercontent.com/26772741/80162274-bad7b780-8587-11ea-9974-0ed7832c664d.png">

**Comment by markcmiller86** [comment]
> @brugger shouldn't the Transform operator with the attributes shown in the attachment do the same thing?

@griffin28 yes...and I believe it is possible though I think you may need to take care with offsets by including a second transform operator that performs a *translation* too. Note that I don't think you can perform *both* translation and coordinate transformation in a *single* **Transform** operator instance. You get one or the other.

I was going to ask why @brugger1 used Expressions + **Displace** operator whereas last time I did something similar I wound up using expressions plus two **Transform** operators. I will go look again what I had to do. I should have saved/attached a session file somewhere here on GitHub 😮

**Comment by griffin28** [comment]
Thanks @markcmiller86 I applied Eric's prescription on the rect3d.silo dataset and also applied the Transform operator and got the attached results. The mesh was produced by the Transform operator and the pseudo color plot is using Eric's method. I didn't expect them to be that different.

<img width="1191" alt="Screen Shot 2020-04-23 at 5 24 23 PM" src="https://user-images.githubusercontent.com/26772741/80163270-7c8fc780-858a-11ea-8409-b0c4b2245afc.png">

**Comment by brugger1** [comment]
They are different because my equations are for spherical to cartesian and the transform operator for the above image is set to cylindrical to cartesian. I believe the image is correct for that case.
