### ISSUE TITLE
Error reading exodus data

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#48]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi,

I am running into a problem with the exodusII with new-ish version of the exodus libraries from https://github.com/gsjaardema/seacas.git

I am attaching 2 versions of the same file. Same code, linked with version 7.08f (git commit 5f9b73fc045114734c0dd4758331867c1b0a8d26) then  version 7.18f (git commit c21ac6a1e7379fc1296baa1c27c59c5080384c67) of the exodus libraries.
Both files open OK in visit, but nodal and zonal fields do not display in the variable list in the later one (try Displacement_X at the last step for a non-zero variable).
I confirmed with Greg Sjaardema, the head developer for the exodus libraries, that both files are fully compliant. Both files open fine with paraview 5.8.0 and 5.7.0.
Using ncdump and diff, I see that the only difference between the files is the suppression of three dimensions in the more recent file.
```
MacBookGray:~ $ ncdump Uniaxial-7.08f.exo > Uniaxial-7.08f.txt
MacBookGray:~ $ ncdump Uniaxial-7.18f.exo > Uniaxial-7.18f.txt
MacBookGray:~ $ diff Uniaxial-7*txt
1c1
< netcdf Uniaxial-7.08f {
---
> netcdf Uniaxial-7.18f {
3,5d2
<        len_string = 33 ;
<        len_line = 81 ;
<        four = 4 ;
80,81c77,78
<                :api_version = 7.08f ;
<                :version = 7.08f ;
---
>                :api_version = 7.18f ;
>                :version = 7.18f ;
```
I have not identified the exact changeset of the exodus libraries at which the issue appeared, but I can do it if it will help debugging the problem with the reader.
 
Any idea of what is going on, and possible fix beside rolling back to an ancient version of the exodus libraries (current version is 8.01)?

Best regards,
Blaise

**Comment by biagas** [comment]
@bourdin
Thanks for the question and for providing sample data files.

VisIt's exodus reader doesn't actually utilize the exodus libraries, but instead uses netcdf libraries (currently version 4.1.1).

I can submit a ticket to update our reader to account for format changes.  
Will send you a link when that ticket is created.

Kathleen

**Comment by bourdin** [comment]
Hi Kathleen,

Is there a specific reason why the exodus reader does not use the exodus library?
It seems counterproductive to reimplement a full reader, and this specific example shows how it can be a source of incompatibilities.
FWIW, the VTK reader does rely on the official exodus implementation (which does not suffer from the bug I highlighted). Can visit use VTK readers instead of its own?

Regards,
Blaise


On Apr 29, 2020, at 12:14 PM, Kathleen Biagas <notifications@github.com<mailto:notifications@github.com>> wrote:



@bourdin<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbourdin&data=02%7C01%7Cbourdin%40lsu.edu%7Ccc431b64dc4844ca334208d7ec60bdf2%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237772562962238&sdata=HfTTY0w83tZ8Dw2tRmAsdUesylpPSkXPq%2FuU1jIzykw%3D&reserved=0>
Thanks for the question and for providing sample data files.

VisIt's exodus reader doesn't actually utilize the exodus libraries, but instead uses netcdf libraries (currently version 4.1.1).

I can submit a ticket to update our reader to account for format changes.
Will send you a link when that ticket is created.

Kathleen

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvisit-dav%2Flive-customer-response%2Fissues%2F48%23issuecomment-621346301&data=02%7C01%7Cbourdin%40lsu.edu%7Ccc431b64dc4844ca334208d7ec60bdf2%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237772562962238&sdata=0aAD2n%2FHLbYxNqvOz5Z3kR8A%2Bjnmm%2BiF%2FC%2FlQMZu%2FXY%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABBJTKFHNFHRKVDBUMTRETRPBN6LANCNFSM4MT46MIA&data=02%7C01%7Cbourdin%40lsu.edu%7Ccc431b64dc4844ca334208d7ec60bdf2%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237772562972234&sdata=n0cqxoNLFA%2FVCz8mEmxE1VtquVPpv1lTJJqVYnURPnc%3D&reserved=0>.

--
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin

**Comment by biagas** [comment]
I believe @markcmiller86 would be better able to answer regarding the decision not to use the exodus libraries.

**Comment by biagas** [comment]
Based on the sample files and your comment regarding missing dimension lines in newer files, I think I can get a fix in for our next release 3.1.2.  Barring any other significant changes in newer files.

**Comment by biagas** [comment]
entered ticket [4658](https://github.com/visit-dav/visit/issues/4658)

**Comment by biagas** [comment]
@bourdin 
Here is a zip file with the modified Exodus reader. 
[Exodus.zip](https://github.com/visit-dav/live-customer-response/files/4554472/Exodus.zip)

See the [wiki](http://visitusers.org/index.php?title=Building_plugins_using_CMake) that describes how to build the plugin against an installed version of VisIt.

Let me know if you need help building, or if you encounter problems with the new reader.

I tested with our available exodus sample data, some files from VTK, and your sample files.

**Comment by bourdin** [comment]
Thanks for sending the plugin and the instructions. I was able to install it on my machines

Regards,
Blaise


On Apr 29, 2020, at 3:47 PM, Kathleen Biagas <notifications@github.com<mailto:notifications@github.com>> wrote:



@bourdin<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbourdin&data=02%7C01%7Cbourdin%40lsu.edu%7Cf399d33f27a44ed53dda08d7ec7e83d6%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237900437492351&sdata=Vg4qU8u7ITCv4tRznIzknNe8su4YTCK5kHr9pdbtuPI%3D&reserved=0>
Here is a zip file with the modified Exodus reader.
Exodus.zip<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvisit-dav%2Flive-customer-response%2Ffiles%2F4554472%2FExodus.zip&data=02%7C01%7Cbourdin%40lsu.edu%7Cf399d33f27a44ed53dda08d7ec7e83d6%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237900437492351&sdata=kBvbgAIUBsfXfywftWGf6S00KuoUAKT5pNOmQqln8pc%3D&reserved=0>

See the wiki<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fvisitusers.org%2Findex.php%3Ftitle%3DBuilding_plugins_using_CMake&data=02%7C01%7Cbourdin%40lsu.edu%7Cf399d33f27a44ed53dda08d7ec7e83d6%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237900437502340&sdata=oi4x8AuV6BUdoQ7usQlaYxTt1ADbGADE65oerJlm8Ls%3D&reserved=0> that describes how to build the plugin against an installed version of VisIt.

Let me know if you need help building, or if you encounter problems with the new reader.

I tested with our available exodus sample data, some files from VTK, and your sample files.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvisit-dav%2Flive-customer-response%2Fissues%2F48%23issuecomment-621454814&data=02%7C01%7Cbourdin%40lsu.edu%7Cf399d33f27a44ed53dda08d7ec7e83d6%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237900437502340&sdata=NZ%2Fkq%2BT3XwZZQbT9QByJ%2BiTO7W0%2FkeMCse4CjrGDWa4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAABBJTPVII5VLZTNPRTKWXLRPCG5TANCNFSM4MT46MIA&data=02%7C01%7Cbourdin%40lsu.edu%7Cf399d33f27a44ed53dda08d7ec7e83d6%7C2d4dad3f50ae47d983a09ae2b1f466f8%7C0%7C0%7C637237900437512333&sdata=8huuxzUN35uiWgbbf2JNHfagVuqxuiCG2%2FWO0q87C1o%3D&reserved=0>.

--
A.K. & Shirley Barton Professor of  Mathematics
Adjunct Professor of Mechanical Engineering
Adjunct of the Center for Computation & Technology
Louisiana State University, Lockett Hall Room 344, Baton Rouge, LA 70803, USA
Tel. +1 (225) 578 1612, Fax  +1 (225) 578 4276 Web http://www.math.lsu.edu/~bourdin
