### ISSUE TITLE
Consolidating vtk files to single file when converting from samrai

### ISSUE THREAD

**Issue by rusu24edward** [visit-dav/live-customer-response#55]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
Hello, 

I have a parallel simulation which outputs data in SAMRAI format, so there is a file "summary.samrai" followed by "processor_cluster.00000.samrai", "processor_cluster.00001.samrai" etc. I am then exporting this data to vtk using ExportDatabase. 

Is there a way to consolidate into a single vtk (or vtu, vtr etc) file out associated with the summary.samrai using this export function? 

Thank you, 
Alex

**Comment by rusu24edward** [comment]
Hi Alex,

I am not aware of this capability in visit. Do you have a specific reason for wanting to have a single vtk file instead of the samrai summary file?

**Comment by markcmiller86-visit** [comment]
Dear Edward,

I was having problems with getting the data to read as one block (not as a
piece of a decomposed domain) when exported to vtr in some scripts. However
I believe have found workarounds and it seems to be going fine. The other
issue is that it is quite easy to fill the cluster allocation for number of
files if running lots of simulations. This can be mitigated with some
movement, zip files, etc though, so this is not enough need to make this a
priority.

Regardless, I am moving on and things are working well. Thank you for the
reply and assistance.

Thank you,
Alex

**Comment by markcmiller86** [comment]
Alex, you mention SAMRAI and I am somewhat familiar with that framework's HDF5 output. Typically, it creates a file-per-processor *plus* a *summary* (or sometimes also called a *master* or *root*) file that contains information about all the different mesh pieces and their files.

Depending on the scale at which the SAMRAI-based simulation runs (a few tens of MPI-ranks versus tens of thousands of MPI-ranks), assembling all the pieces together into a *single* monolithic (and very large) chunk of mesh may not be practical. 

That said, I can think of a couple of different ways you can do this. 

1. Try the **Merge** operator (under **Operators**-->**Geometry**-->**Merge**). To do this correctly, you first need to determine the *minimum edge length* of the non-ghost zones of your mesh (to know what this value is, use *Expressions* to define a variable using the `min_edge_length()` mesh-quality expression and query the min-max of that expression in VisIt). The reason for this is that the **Merge** operator uses a *distance threshold* between points to find those nodes in the mesh to *treat as the same node*. Knowing the minimum edge length of the mesh means you've got a shot at selecting a threshold that will correctly ignore points that are simply *close* because they belong to the same teeny, tiny mesh zone. This is NOT a *perfect* solution though and can sometimes not work. Also, check the box in the **Merge** operator attributes for `Merge across all processors?`. If the mesh scale is small enough (or the node's where you are running have enough memory), it should be able to complete this operation merging all the pieces to a single MPI rank.
1. Export to VTK as before.

Another option is to export to Silo and select `Coordinate parallel writes with groups` and then enter a `write group size` that is equal to the number of original file parts you have. This *however* will only combine everything into a *single* Silo file. The Silo file you end up with will not contain a single mesh but instead all the original mesh pieces just in a single file.

**Comment by markcmiller86** [comment]
Alex, on this issue...

> The other issue is that it is quite easy to fill the cluster allocation for number of files if running lots of simulations. This can be mitigated with some movement, zip files, etc though, so this is not enough need to make this a priority.

Does your workflow involve *local burst buffers* by any chance? And, is the *allocation* you mention filling related to an *i-node* quota or a total storage quota or something else?
