### ISSUE TITLE
curve file from lineout in CLI

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#58]
Good morning,
 
I am trying to output a curve file from a lineout using the CLI on VisIt 3.1.1 for Windows. I do not seem to be producing a curve file with the code snippet below.  It is not clear to me from the CLI manual how to accomplish this.
 
    AddPlot("Pseudocolor","p")
    DrawPlots()
    s = SaveWindowAttributes()
    s.format = s.CURVE
    s.fileName = workdir+"\\mycurvefile"
    SetSaveWindowAttributes(s)
    Lineout((0,0), (70,0))
    SetActivePlots(1)
    SaveWindow()
 
Regards,
Luis Costa

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Luis,

The curve from the Lineout goes to a new window, which assuming you have only 1 window would be window 2. You will need to change the active window to window 2 before saving the curve. You can replace

SetActivePlots(1)

with

SetActiveWindow(2)

since the save window will save all the curves in the active window.

Eric

**Comment by markcmiller86-visit** [comment]
Eric,



Thanks. That works.



Do you know how to get VisIt to run without opening or drawing any windows purely in a python module, i.e. python -m myscript.py, and not using visit -cli -nowin?



Regards,

Luis Costa

________________________________
From: Eric Brugger via visit-users [visit-users@elist.ornl.gov]
Sent: Wednesday, May 06, 2020 10:40 AM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] curve file from lineout in CLI (#58)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.

________________________________



Hi Luis,

The curve from the Lineout goes to a new window, which assuming you have only 1 window would be window 2. You will need to change the active window to window 2 before saving the curve. You can replace

SetActivePlots(1)

with

SetActiveWindow(2)

since the save window will save all the curves in the active window.

Eric

**Comment by markcmiller86-visit** [comment]
Eric,



Sorry. Figured it out.

AddArgument("-nowin")



Regards,

Luis Costa

________________________________
From: Costa, Luis CIV USARMY CCDC AC (USA)
Sent: Wednesday, May 06, 2020 10:56 AM
To: visit-dav/live-customer-response; VisIt software users community; visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: RE: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] curve file from lineout in CLI (#58)


Eric,



Thanks. That works.



Do you know how to get VisIt to run without opening or drawing any windows purely in a python module, i.e. python -m myscript.py, and not using visit -cli -nowin?



Regards,

Luis Costa

________________________________
From: Eric Brugger via visit-users [visit-users@elist.ornl.gov]
Sent: Wednesday, May 06, 2020 10:40 AM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [Non-DoD Source] [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] curve file from lineout in CLI (#58)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.

________________________________



Hi Luis,

The curve from the Lineout goes to a new window, which assuming you have only 1 window would be window 2. You will need to change the active window to window 2 before saving the curve. You can replace

SetActivePlots(1)

with

SetActiveWindow(2)

since the save window will save all the curves in the active window.

Eric
