### ISSUE TITLE
 Slow Rendering in VisIt for FLASH

### ISSUE THREAD

**Issue by biagas** [visit-dav/live-customer-response#68]
Hi Rick,

Thank you for bringing this to our attention again. You should definitely be using a parallel engine.

Does the slow rendering exhibit right from the start, with the first timestep? Or does the problem get worse as you advance through time? If the second, it may indicate a memory leak. In which case, you might work-around the problem by clearing the engine cache at each timestep:  File->Compute engines->Clear cache. Please note, I am not suggesting this is a permanent fix.

Also, are you using any of my previous suggestions?

Kathleen

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---
I have a serious problem drawing pseudo-color plots in VisIt of FLASH data. There are large data sets (~0.5 GB per time step). They are highly resolved AMR runs. A single processor VisIt render will take > 30 minutes - IF it ever finishes. The problem seems worse on VisIt 3.1.1 than VisIt 2.13. VisIt basically freezes with no CPU activity in many cases. VisIt is running on a 12-core Mac Pro with > 100 GB of memory. VisIt allocates ~ 5 GB for the problem.

I don’t know if this situation can be improved with multi-processors but the FAILURE of VisIt to render large files suggests a more fundamental problem than just computing horsepower.

Rick

**Comment by biagas** [comment]
I have entered a [ticket](https://github.com/visit-dav/visit/issues/4750) to look into the possibility of a memory leak with the flash plugin.

**Comment by markcmiller86-visit** [comment]
Dear Kathleen,

The initial time step has little AMR info so it renders 3-4X faster than a later time step.

From your prior suggestions: Controls/Subset/AMR_mesh/Levels option to reduce the number of AMR levels was successful in giving me a factor of two or so improvement in Draw. This works as I limit the AMR levels used in FLASH to three. I always use this option. I have not tried the clear cache option. None of your other suggestions had any effect on render time.

I have tried to go to higher refinement in FLASH and that has taken the render time to infinity.

I’ll give the Clear Cache a shot.

Rick

Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu<mailto:spielman@lle.rochester.edu>



On May 19, 2020, at 1:34 PM, Kathleen Biagas via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

Thank you for bringing this to our attention again. You should definitely be using a parallel engine.

Does the slow rendering exhibit right from the start, with the first timestep? Or does the problem get worse as you advance through time? If the second, it may indicate a memory leak. In which case, you might work-around the problem by clearing the engine cache at each timestep: File->Compute engines->Clear cache. Please note, I am not suggesting this is a permanent fix.

Also, are you using any of my previous suggestions?

Kathleen

We're trying to combine visit-users email list with GitHub issues<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_wiki_How-2Dthe-2Dnew-2DGitHub-2Dvisit-2Dusers-2DEmail-2DIntegration-2DWorks&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=touXYRgOrpmX1fvFQs52qFpTqQ2Aw_Nl8iAGVFe25hE&e=>.
When replying on visit-users, please reply only to emails with a Subject
line that includes [visit-dav/live-customer-response].

________________________________

I have a serious problem drawing pseudo-color plots in VisIt of FLASH data. There are large data sets (~0.5 GB per time step). They are highly resolved AMR runs. A single processor VisIt render will take > 30 minutes - IF it ever finishes. The problem seems worse on VisIt 3.1.1 than VisIt 2.13. VisIt basically freezes with no CPU activity in many cases. VisIt is running on a 12-core Mac Pro with > 100 GB of memory. VisIt allocates ~ 5 GB for the problem.

I don’t know if this situation can be improved with multi-processors but the FAILURE of VisIt to render large files suggests a more fundamental problem than just computing horsepower.

Rick

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_68&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=vyBqM2eSZaxQNOtjFrPyCcD3i9CdzE4y8hHd2Y99HeE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZAKPQOK6NPEFDBVWI3RSK7JDANCNFSM4NFGRO3A&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=BjKqEVjJMtEnkFZngpYuSOgwFKCctapq54BuCJdca50&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=hY-QHajPkROz5kiTl2loPCLsfOzxhvTagI3ulJamM4I&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=FCVfsm-xXaj_Y-ylSk2Ksy6qtljHeHVC77ZDsiM0UV8&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=Zwja4ky-uwfn-SMsiP-Z150RjXwXYxUF202MXO4N-S4&s=OjsXpyHeYSWRWBFoOpxGVfWuOR6NdaXla-h75D8qxMo&e=

**Comment by markcmiller86-visit** [comment]
Dear Kathleen,

I got VisIt to run multi-processor. The render is > 20X faster with 8 threads. Wow. It is now usable.

Rick

Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu<mailto:spielman@lle.rochester.edu>



On May 19, 2020, at 1:36 PM, Kathleen Biagas via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



I have entered a ticket<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_visit_issues_4750&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=hIUZxsjA_Ju_o58Tkg3fvIHehgks1U_wj9VkzxyaU6c&e=> to look into the possibility of a memory leak with the flash plugin.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_68-23issuecomment-2D630972723&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=P3YCEsOHFgPh5zdP9UfI8pPBLFMItO7mRnYqfJfqfTM&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZEXAMMDR3LFFGAZWW3RSK7TDANCNFSM4NFGRO3A&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=KVQxmascgCtZ-soUSdDI4c0FQ4n-v1Jk9oLcb93Ed1M&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=c73rHRbWA5iE86dGJAqFEctsFyhxJBphYB1IsOqJUps&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=UkjB7Zyx3-y0vjwGfwxj7R0YyzjnUc9cAgohWLPCP_0&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=GhINacFAEXgtYCFNWyIY6X7-NcmSPIlSSt3aJ81IccQ&s=03BGHaAhMYjV4i2W-GHSlORDfQ7BF7QchNZ_LCefvzI&e=

**Comment by biagas** [comment]
Glad you are finally running in parallel and seeing the improvement.
