### ISSUE TITLE
Having a curve show up on a Projected 3D plot?

### ISSUE THREAD

**Issue by griffin28** [visit-dav/live-customer-response#74]
We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

Hi Cyrus,
Hope you are doing well! I am having issues with having a 1D curve show up on a plot that has been projected onto 2D. In the image below, I have a 3D sph simulation that has been projected into 2D. I then overlay a curve called “backsplash”, but it doesn’t show up very clearly in the image (I tried changing colors too). It looks like the curve is plotted behind? How do I get it to show up more clearly? Thanks for your help!
 
Best,
Karen

![image001](https://user-images.githubusercontent.com/26772741/83217336-5aa4da00-a120-11ea-9b63-b88deed5a722.png)

**Comment by brugger1** [comment]
I was able to replicate this with globe.silo. I created a pseudocolor plot of u, applied the threshold operator to turn the mesh into a point mesh, then applied the project operator and drew the plot. I increased the point size to 20 just to make the points take up some space on the screen, since the points were pretty sparse. I then overlayed a curve plot from a curve I created with a line out. The points were rendered on top of the curve. I then added a projected mesh plot and that ended up on top of the points. So it is something specific to the curve plot, possibly the rendering order or shift factor.

**Comment by brugger1** [comment]
I looked at the curve plot code and saw that it wasn't setting a shift factor, whereas most other plots were setting the shift factor between 0.5 and 0.9 so that they would always be in front of pseudocolor plots, which had a shift factor of 0.

I modified avtCurvePlot.C to set behavior->SetShiftFactor(0.9) in CustomizeBehavior. This fixed the problem. This fixes the problem, but we should have a quick discussion with Kathleen to verify that this is the best solution. I noticed the curve plot also had behavior->SetRenderOrder(MUST_GO_LAST), so I would think that would have been enough since the pseudocolor plot has behavior->SetRenderOrder(DOES_NOT_MATTER).

**Comment by biagas** [comment]
@brugger1 I think the Render order behavior should be investigated to determine if Curve plots are indeed being added to the renderer in last position. 

I don't think Curve plot should always be shifted.  Perhaps the shift factor could be set for Curve plots only if non-curve plots are present in the same window? (If Render order is being maintained, and using shift is the only way to fix.)

**Comment by markcmiller86-visit** [comment]
I believe the render order is being handled properly. I looked at VisWinPlots::OrderPlots and I don’t see why this would fail given the Render order values for Pseudocolor and curve. Also, the ordering is correct when using pseudocolor plots of polygons in 2d. The problem is only with all points. I suspect the problem is the fact that we are using z buffering in this case, which would explain why changing the shift factor changes things. I found this code in the Pseudocolor plot.

bool
avtPseudocolorPlot::NeedZBufferToCompositeEvenIn2D(void)
{
    if (behavior->GetInfo().GetAttributes().GetTopologicalDimension() <= 1)
    {
        if (atts.GetPointType() != Point)
            return true;
        else if (atts.GetPointSizePixels() != 1)
            return true;
    }

    return false;
}

which to me implies for point meshes we are turning on z buffering for almost all cases, making the rendering order insufficient.
