### ISSUE TITLE
VisIT Movie Generation Failed

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#83]
Sear VisIT Help Desk and Users, 

I am trying to create a movie based on screen capture png stills. The screen display is fine and the PNGs appear to be fine (thumbnail). When I look at the movie (Quicktime or VLC) I get the frames shown below. Clearly, there is a rastering error.

<img width="973" alt="live_customer-response-2020-06-15" src="https://user-images.githubusercontent.com/1102718/84691019-4a4e7680-aef8-11ea-9b42-7aab381f8c51.png">

The encoding process shows continual overflow errors.

Encoding frame 265 .........................................................
vbv_delay overflow!
vbv_delay overflow: 705334
Encoding frame 266 .........................................................
vbv_delay overflow!
vbv_delay overflow: 708330
Encoding frame 267 .........................................................
vbv_delay overflow!
vbv_delay overflow: 708906
Encoding frame 268 .........................................................
vbv_delay overflow!
vbv_delay overflow: 711164
Encoding frame 269 .........................................................
vbv_delay overflow!
vbv_delay overflow: 713824
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

I have tried this on single processor (takes forever) and 4 processors (much faster). They give the same bad result. Any suggestions?

Rick

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Rick,

It looks like you are using the mpeg encoder that ships with VisIt. It is not the best movie encoder, although it should work properly. I frequently see the vbv_delay errors and those don't seem to affect the output.

VisIt can also use the ffmpeg movie encoder which is a better encoder. If VisIt finds it in your search path, it will use it over the built in one. We don't ship VisIt with ffmpeg because of licensing issues, but you are free to install it and then add it to your search path.

**Comment by brugger1** [comment]
If you need help with installing ffmpeg, I can provide help if you let me know what operating system you are running on (Linux, Mac, Windows).

Eric

**Comment by markcmiller86-visit** [comment]
Eric,

I am running on a MacBook Pro with Mojave. I run the multi-processor VisiIT from the terminal.

I could use the help installing ffmpeg.

Rick


On Jun 15, 2020, at 12:16 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



If you need help with installing ffmpeg, I can provide help if you let me know what operating system you are running on (Linux, Mac, Windows).

Eric

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_83-23issuecomment-2D644290518&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=1pEeuBsEBVzybw3Mt6n7Vc98qrGJbKmpb0aEjMojIdU&s=EqlAxm9rXdyN1U7pHJ-2ZFTuFqp1VEio2ZhLcjWhp-s&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZCY5VQNLKZVYXXIINDRWZQOJANCNFSM4N6NDSKQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=1pEeuBsEBVzybw3Mt6n7Vc98qrGJbKmpb0aEjMojIdU&s=1BnevW4O-yhmGXkv8pzqypWOWC_q2mdYoHT1MolStFE&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=1pEeuBsEBVzybw3Mt6n7Vc98qrGJbKmpb0aEjMojIdU&s=HEcbpdcVG0gv7gXTxdshd7B9oD8CZMsJHKMOoTQZMCs&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=1pEeuBsEBVzybw3Mt6n7Vc98qrGJbKmpb0aEjMojIdU&s=QgDKwhCFEPS30216ilNkT5Oq3_T-lDH6qlvan1ytA3g&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=1pEeuBsEBVzybw3Mt6n7Vc98qrGJbKmpb0aEjMojIdU&s=JfDF8-t1kmrT3o0iDe8gyqkBmrpm-xoGFooOCy2f8LA&e=

**Comment by brugger1** [comment]
You can go to https://www.ffmpeg.org/download.html and the scroll a bit down until you get to a section labeled "Get packages & executable files".

Now click the Apple logo on the right side. This change the text below the 3 logos to "macOS". Under that click on "Static and shared builds for macOS 64-bit".

There are now several pull downs to set. Select "4.2.3" for the Version, "macOS 64-bit" for the Architecture, "static" for the Linking, and "LGLP 3.0" for the License. Now you can click on "Download bulid" to download the build.

At this point you can install it as you would a macOS package. I don't know details of adding it to your search path on macOS. If you need help with that I can ask some of our mac developers. I'm only familiar with Linux and Windows.

**Comment by markcmiller86-visit** [comment]
Dear Eric,

I have downloaded the zip filem for the Static and Shared build and unzipping gives me a folder containing multiple items. The /bin/ directory has the juicy stuff but I am unsure where to install the Unix Executible. In fact, I am not sure what the app does.

[cid:C2B907B5-922D-4984-BA37-9CB3E112F898@hsd1.nm.comcast.net.]

Double clicking on the ffmpeg app gives. I could open it from a Terminal Window but I would just get a prompt.

Last login: Mon Jun 15 11:54:57 on ttys005
RBS-MacBook-Pro:~ rbspielman$ /Users/rbspielman/Downloads/ffmpeg-4.2.3-macos64-static-lgpl/bin/ffmpeg ; exit;
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libaom --enable-appkit --enable-avfoundation --enable-coreimage --enable-audiotoolbox
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I could use help here.

Rick


On Jun 15, 2020, at 12:37 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



You can go to https://www.ffmpeg.org/download.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ffmpeg.org_download.html&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=u71QzIzcgSjfpMdR3nEzANgNJIzaBZqUGvu0Cp5xR6I&e=> and the scroll a bit down until you get to a section labeled "Get packages & executable files".

Now click the Apple logo on the right side. This change the text below the 3 logos to "macOS". Under that click on "Static and shared builds for macOS 64-bit".

There are now several pull downs to set. Select "4.2.3" for the Version, "macOS 64-bit" for the Architecture, "static" for the Linking, and "LGLP 3.0" for the License. Now you can click on "Download bulid" to download the build.

At this point you can install it as you would a macOS package. I don't know details of adding it to your search path on macOS. If you need help with that I can ask some of our mac developers. I'm only familiar with Linux and Windows.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_83-23issuecomment-2D644307667&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=-tsH-_FRBrlQfDtRQq5SyOYPLlDFdutSSK0NdnCleB8&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZEQHY44XAPJXXCIXPTRWZS43ANCNFSM4N6NDSKQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=SdZIDF-a0-lgdcDhEzSevF3b1KB46ED1pfSltNelRhE&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=gAfA14IU6wnBdpkqukI7o-sGrjKvQ0-8Q--jaP0DWsg&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=VrzP5alvrd_Hf_mCkLZqkwJXZxSAn5pyHuVK3dYYzw0&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=UGTiW72SwOqIBG9bEdfn9fbCMtpX50Mf36J7Q3FbuLM&s=bNJ-nrAE0QZpryUx8GrXCigIVUi_IUyOHx9Y73ZDAl4&e=

**Comment by brugger1** [comment]
Hi Rick,

I believe all you need to do is copy the ffmpeg executable into a directory that is in your search path. You could even install it into the VisIt bin directory, which, for example, would be visit/3.1.2/darwin-x86_64/bin for VisIt 3.1.2.

**Comment by markcmiller86-visit** [comment]
Eric,

I am not sure what my VisIT search path is as I never set it or changed it. I can easily place the executable in the /visit/…./bin/ path. I’ll give that a try.

Rick


On Jun 15, 2020, at 1:46 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

I believe all you need to do is copy the ffmpeg executable into a directory that is in your search path. You could even install it into the VisIt bin directory, which, for example, would be visit/3.1.2/darwin-x86_64/bin for VisIt 3.1.2.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_83-23issuecomment-2D644340759&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=VPxnHPaZXoqca_mDuwFbDHG_y8qaBCfqm5AWKAqQAos&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZCM7IXPBVHXU6M25PTRWZ3A5ANCNFSM4N6NDSKQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=-TLvED6rbG-f6dhKWKP1f0DI9i9d6YanEP8GuW-P3BQ&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=ij8Lkh3JF5YYqOwbK93uj_RK_LqJU2j4TTLNuwN0bwg&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=qqNoGHIWJewF3vCK70vO1h_fb4xYuSKmcldR9LjUDgY&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=rmY5QDw9QnGTqLo__OLdJ4d7RbbJe3Ey-UTvBo8nRp0&e=

**Comment by markcmiller86-visit** [comment]
Further to Eric's suggestation, this is a good link with different options 
to install ffmpeg on macOS,

 	https://superuser.com/questions/624561/install-ffmpeg-on-os-x

Regards,
Marcelo

**Comment by markcmiller86-visit** [comment]
Dear Eric,

The actual path on a Mac is:

/Applications/visit.app/Contents/Resources/bin/

When I placed the binary in /bin/ everything worked just fine!! Thanks for your help.

Rick

Dr. Rick B. Spielman
Senior Scientist
University of Rochester
Laboratory for Laser Energetics
250 East River Road
Rochester, NY 14623
Office: 585-275-2732
Cell: 505-715-0416
E-mail: spielman@lle.rochester.edu<mailto:spielman@lle.rochester.edu>



On Jun 15, 2020, at 1:46 PM, Eric Brugger via visit-users <visit-users@elist.ornl.gov<mailto:visit-users@elist.ornl.gov>> wrote:



Hi Rick,

I believe all you need to do is copy the ffmpeg executable into a directory that is in your search path. You could even install it into the VisIt bin directory, which, for example, would be visit/3.1.2/darwin-x86_64/bin for VisIt 3.1.2.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_visit-2Ddav_live-2Dcustomer-2Dresponse_issues_83-23issuecomment-2D644340759&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=VPxnHPaZXoqca_mDuwFbDHG_y8qaBCfqm5AWKAqQAos&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AOLAYZCM7IXPBVHXU6M25PTRWZ3A5ANCNFSM4N6NDSKQ&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=-TLvED6rbG-f6dhKWKP1f0DI9i9d6YanEP8GuW-P3BQ&e=>.

--
VisIt Users Wiki: https://urldefense.proofpoint.com/v2/url?u=http-3A__visitusers.org_&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=ij8Lkh3JF5YYqOwbK93uj_RK_LqJU2j4TTLNuwN0bwg&e=
Frequently Asked Questions for VisIt: https://urldefense.proofpoint.com/v2/url?u=https-3A__wci.llnl.gov_simulation_computer-2Dcodes_visit_FAQ.html&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=qqNoGHIWJewF3vCK70vO1h_fb4xYuSKmcldR9LjUDgY&e=
To Unsubscribe: send a blank email to visit-users-unsubscribe@elist.ornl.gov<mailto:visit-users-unsubscribe@elist.ornl.gov>
More Options: https://urldefense.proofpoint.com/v2/url?u=https-3A__elist.ornl.gov_mailman_listinfo_visit-2Dusers&d=DwICAg&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=hChrFuoqUtPzbqaCnW9fLyGmpeZx_HQ49112JCNLTZA&m=0O6LHCZxhWIbWZz_RREW5GEuPFNcD6CkcXuqhJgP_ck&s=rmY5QDw9QnGTqLo__OLdJ4d7RbbJe3Ey-UTvBo8nRp0&e=

**Comment by brugger1** [comment]
Awesome! You're welcome and thanks Marcelo!
