### ISSUE TITLE
Visit on Pleiades

### ISSUE THREAD

**Issue by brugger1** [visit-dav/live-customer-response#98]
Hello,

I’m trying to load a 500 Gb file into Visit on Pleiades. Unsuccessfully so far. The same file works fine on Comet with 10 Haswell nodes (240 cores). I use supposedly the same haswell nodes on Pleiades and it’s not enough memory. In reality, I asked 10 times more memory using Ivy nodes with the same failure.

Has anybody any idea about what’s going on? 

All the best,
Nick.

Nikolai V Pogorelov
Department of Space Science
University of Alabama in Huntsville
320 Sparkman Dr.
Huntsville, AL 35805
Tel. 256-961-7617

We're trying to [combine `visit-users` email list with GitHub issues](https://github.com/visit-dav/live-customer-response/wiki/How-the-new-GitHub-visit-users-Email-Integration-Works).
When replying on `visit-users`, please reply **only** to emails with a *Subject*
line that includes `[visit-dav/live-customer-response]`.

---

**Comment by brugger1** [comment]
Hi Nick,

Can you give a little bit more information.

What is the file format of the data?
Are you also using 10 haswell nodes on Pleiades?
Does Pleiades have the same amount of memory per node as Comet?
What are the versions of VisIt you are using on Comet and Pleiades?

Eric

**Comment by markcmiller86-visit** [comment]
Hi Eric,

The details are below.

Comet.

![comet](https://user-images.githubusercontent.com/1102718/86794266-28d93a00-c021-11ea-88ac-1bba5a461ce6.png)

Pleiades.

![pleiades](https://user-images.githubusercontent.com/1102718/86794300-34c4fc00-c021-11ea-9098-521e9f9e9677.png)

I used 3.0.5 on Comet and 3.0.0 on Pleiades.

All the best,
Nick.

From: Eric Brugger via visit-users [mailto:visit-users@elist.ornl.gov] 
Sent: Monday, July 6, 2020 5:26 PM
To: visit-dav/live-customer-response
Cc: Eric Brugger; Subscribed
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Visit on Pleiades (#98)

 

Hi Nick,

Can you give a little bit more information.

What is the file format of the data?
Are you also using 10 haswell nodes on Pleiades?
Does Pleiades have the same amount of memory per node as Comet?
What are the versions of VisIt you are using on Comet and Pleiades?

Eric

**Comment by brugger1** [comment]
Hi Eric,

There’s one more difference. On Comet, we run Visit using the client/remote-host model. On Pleiades, I run Visit there through VNC.

All the best,
Nick.

**Comment by griffin28** [comment]
Nick...what is the file format (e.g. silo)? Also, I'm assuming you meant VisIt version 3.0.2 instead of 3.0.5. This is important because I can compare the changes between versions to see if anything sticks out that could cause this issue.

Also, have you verified that you are actually running in parallel on Pleiades?

-Kevin

**Comment by brugger1** [comment]
Hi Nick,

It looks like Comet and Pleiades have the same amount of memory per node, so I wouldn't expect it to be related memory usage. Client/server versus VNC could certainly affect the rendering. Are you able to render any images when you run on Pleiades, or is it just that particular dataset? Assuming that VisIt works for viewing some datasets, then the most likely thing I can think of is the difference in versions. 3.0.0 was our first release after a major change in underlying libraries and there were quite a few bug fixes over the next several releases of VisIt, so it's possible that a bug got fixed that is causing problems on Pleiades. I would try and get the latest version built and installed on Pleiades.

Eric

**Comment by markcmiller86-visit** [comment]
Hi Kevin,

 

Thank you.  Indeed, this is 3.0.2 on Comet. I use Visit 3.0.0 on Pleiades. I use HDF5 files. Last night, I actually managed to succeed on Pleiades with 20 Haswell nodes, but only 80 processors. 

 

All the best,

Nick.

 

From: Kevin Griffin via visit-users [mailto:visit-users@elist.ornl.gov] 
Sent: Tuesday, July 7, 2020 11:42 AM
To: visit-dav/live-customer-response
Cc: Kevin Griffin; Comment; markcmiller86-visit
Subject: [visit-users] [EXTERNAL] Re: [visit-dav/live-customer-response] Visit on Pleiades (#98)

 

Nick...what is the file format (e.g. silo)? Also, I'm assuming you meant VisIt version 3.0.2 instead of 3.0.5. This is important because I can compare the changes between versions to see if anything sticks out that could cause this issue.

Also, have you verified that you are actually running in parallel on Pleiades?

-Kevin
